### ISSUE TITLE
checkPingTimer taking up idle CPU

### ISSUE THREAD

**Issue by Muesly** [CleverTap/clevertap-ios-sdk#10]
I've profiled my app and putInt:forKey: called in checkPingTimer in the CleverTapSessionManager class is showing significant activity while the app is running.  Something like 10-20% spikes every second or two.  Could this be looked into please?

**Comment by Aditi3** [comment]
Hey Muesly,
Thank you for notifying. We too have noticed it and in the process of removing this continuous ping call.
