### ISSUE TITLE
Provisional pushes and/or Critical Alerts?

### ISSUE THREAD

**Issue by noorulain17** [CleverTap/clevertap-ios-sdk#100]
Does CleverTap SDK support Provisional pushes or Critical alerts?
Reference: https://developer.apple.com/videos/play/wwdc2018/710/

**Comment by Aditi3** [comment]
@noorulain17 Provisional pushes can be implemented on your app side and the push can be sent from the CleverTap. With your implementation, you will get the device token and pass it on for the associated profile. This can be used to send a push from CleverTap.

**Comment by noorulain17** [comment]
Thanks for the clarification, I'll give it a try.
