### ISSUE TITLE
Crash in CTInboxController

### ISSUE THREAD

**Issue by sachinvas-halodoc** [CleverTap/clevertap-ios-sdk#102]
*** _oset_objectAtIndex: index 5 beyond bounds [0 .. 4]

Fatal Exception: NSRangeException
0  CoreFoundation                 0x1876d186c __exceptionPreprocess
1  libobjc.A.dylib                0x19c6ecc50 objc_exception_throw
2  CoreFoundation                 0x187741e1c -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x1875d7610 +[NSInvocation requiredStackSizeForSignature:]
4  CoreFoundation                 0x1875bb9ec -[NSArray getObjects:range:]
5  Foundation                     0x188a31d9c _filterObjectsUsingPredicate
6  Foundation                     0x188962864 -[NSOrderedSet(NSPredicateSupport) filteredOrderedSetUsingPredicate:]
7  HaloDoc                        0x104cd7780 -[CTInboxController unreadMessages] + 160 (CTInboxController.m:160)
8  HaloDoc                        0x104c9878c -[CleverTap getUnreadInboxMessages] + 4111 (CleverTap.m:4111)
9  HaloDoc                        0x1056b1ab4 specialized CleverTapAppInbox.messageCount.getter + 17 (CleverTapAppInbox.swift:17)
10 HaloDoc                        0x1047dc45c closure #1 in AppInboxViewController.setUpInbox() + 63 (AppInboxViewController.swift:63)
11 HaloDoc                        0x1056b1d54 partial apply for closure #1 in CleverTapAppInbox.setInitializedCallBack(_:) (<compiler-generated>)
12 HaloDoc                        0x104771400 thunk for @escaping @callee_guaranteed (@unowned Bool) -> () (<compiler-generated>)
13 HaloDoc                        0x104c98378 __41-[CleverTap initializeInboxWithCallback:]_block_invoke.1828 + 4070 (CleverTap.m:4070)
14 libdispatch.dylib              0x1872c5db0 _dispatch_client_callout
15 libdispatch.dylib              0x1872d4504 _dispatch_async_and_wait_invoke
16 libdispatch.dylib              0x1872c5db0 _dispatch_client_callout
17 libdispatch.dylib              0x1872d37ac _dispatch_main_queue_callback_4CF
18 CoreFoundation                 0x18764d11c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
19 CoreFoundation                 0x187647120 __CFRunLoopRun
20 CoreFoundation                 0x18764621c CFRunLoopRunSpecific
21 GraphicsServices               0x19f212784 GSEventRunModal
22 UIKitCore                      0x18a086ee8 -[UIApplication _run]
23 UIKitCore                      0x18a08c75c UIApplicationMain
24 HaloDoc                        0x1046fc520 main + 13 (AppDelegate.swift:13)
25 libdyld.dylib                  0x1873066b0 start

**Comment by Aditi3** [comment]
hi @sachinvas-halodoc 

Thanks for sharing the stack trace but can share a demo project with us where the issue is reproducible?
Demo project where the crash is reproducible will help in debug further.

**Comment by sachinvas-halodoc** [comment]
Hi @Aditi3,

We are getting this in our Production environment. The max we can do is share the crashes with you. We are really sorry we won't be able to provide reproduction steps or a demo project.

**Comment by Aditi3** [comment]
@sachinvas-halodoc Are you manually integrating CleverTap App Inbox i.e. using Public APIs?

**Comment by sachinvas-halodoc** [comment]
@Aditi3 No

**Comment by Aditi3** [comment]
I have been trying to reproduce the crash but have not been able to until now and don't have a good way to diagnose or debug these crashes without repro steps.
