### ISSUE TITLE
test notification are working but on creating campaign apns bad device token is received

### ISSUE THREAD

**Issue by varunananddudeja** [CleverTap/clevertap-ios-sdk#114]

**Comment by Aditi3** [comment]
hi @varunananddudeja,  The error specifies device token was bad. You get this error when you try to send the notification with the wrong certificate.

Please verify the configuration of the CleverTap dashboard. It should APNs push mode: Development/ Production with a valid development/ production certificate in Push Setting for iOS.

**Comment by varunananddudeja** [comment]
hi @Aditi3, I’m using p8 key and have set APNs push mode as production. Test notifications are working for every device but through campaign some devices do get notification and some devices get this error ‘apns bad device token’.

If certificate was wrong then it shouldn’t have been working for every device. 

Please help.

**Comment by Aditi3** [comment]
Request you to share the campaign link and integration details with our support team so that we can further debug this issue and assist you.

**Comment by varunananddudeja** [comment]
campaign link 
https://eu1.dashboard.clevertap.com/Z8W-897-665Z/targets/1616566168/show.html#overviewPg

app integration
```
CleverTap.setCredentialsWithAccountID(***** andToken: ***)
CleverTap.autoIntegrate()
CleverTap.sharedInstance()?.setInAppNotificationDelegate(self)
```

**Comment by Aditi3** [comment]
Can you please share details with our support team? You can reach out to the CleverTap support team from the CleverTap Dashboard.

**Comment by varunananddudeja** [comment]
@Aditi3 
https://developer.clevertap.com/docs/ios#section-6-ap-ns-bad-device-token

Documentation says- "For example, you have set the APNs push mode in your app to the "development" stage and in the "CleverTap" dashboard you have set up to "production" stage."

How and from where do we set push mode in our app?

**Comment by Aditi3** [comment]
Here is a link to the reference doc to verify your Push mode - https://developer.apple.com/documentation/bundleresources/entitlements/aps-environment

Are you running your Application in Production mode or Development mode?

**Comment by varunananddudeja** [comment]
The build is archived, it is 'production' in DistributionSummary.plist & on clevertap console as well. I don't know what am i doing wrong.

**Comment by ky6a15** [comment]
@bviscovich  Same problem
