### ISSUE TITLE
App Crashed on CTInboxController.m - Line 207

### ISSUE THREAD

**Issue by sakshibala-halodoc** [CleverTap/clevertap-ios-sdk#115]
Crashed: NSManagedObjectContext 0x280bdeff0
0  libobjc.A.dylib                0x1b6356de8 object_getIndexedIvars + 28
1  CoreData                       0x1a7594884 _PFObjectIDFastHash64 + 36
2  CoreFoundation                 0x1a136621c __CFBasicHashRehash + 992
3  CoreFoundation                 0x1a136a174 CFBasicHashRemoveValue + 2384
4  CoreFoundation                 0x1a127ebf8 CFDictionaryRemoveValue + 248
5  CoreData                       0x1a74decc0 -[NSManagedObjectContext(_NSInternalAdditions) _forgetObject:propagateToObjectStore:removeFromRegistry:] + 124
6  CoreData                       0x1a75d03c0 -[NSManagedObjectContext _didSaveChanges] + 3156
7  CoreData                       0x1a7499b78 -[NSManagedObjectContext save:] + 2956
8  HaloDoc                        0x104eae03c -[CTInboxController _save] + 207 (CTInboxController.m:207)
9  HaloDoc                        0x104eadf10 __37-[CTInboxController _deleteMessages:]_block_invoke + 195 (CTInboxController.m:195)
10 CoreData                       0x1a75d50f8 developerSubmittedBlockToNSManagedObjectContextPerform + 164
11 libdispatch.dylib              0x1a0f2ddb0 _dispatch_client_callout + 20
12 libdispatch.dylib              0x1a0f3510c _dispatch_lane_serial_drain + 580
13 libdispatch.dylib              0x1a0f35c5c _dispatch_lane_invoke + 408
14 libdispatch.dylib              0x1a0f3fd78 _dispatch_workloop_worker_thread + 708
15 libsystem_pthread.dylib        0x1ecde9814 _pthread_wqthread + 276
16 libsystem_pthread.dylib        0x1ecdf076c start_wqthread + 8
<img width="1268" alt="Screenshot 2021-03-24 at 2 15 52 PM" src="https://user-images.githubusercontent.com/72126135/112327014-12702d00-8cdb-11eb-899a-2155fead943f.png">

**Comment by Aditi3** [comment]
Could you provide us with more information or steps to reproduce the same?

**Comment by sakshibala-halodoc** [comment]
Its happening on our live app and we don’t have the steps to reproduce.
