### ISSUE TITLE
After update podfile getting issue with count variable.

### ISSUE THREAD

**Issue by manojkraftly** [CleverTap/clevertap-ios-sdk#12]
![screen shot 2018-05-10 at 11 12 03 am](https://user-images.githubusercontent.com/36626338/39853981-026cd4ea-5443-11e8-945c-f63e06071792.png)
Please check screen shot here i am getting error:-
**Multiple methods named 'count' found with mismatched result, parameter type or attributes**
Please let me know solution for it, because i used count with dictionary more than 1000 times.
![screen shot 2018-05-10 at 11 02 46 am](https://user-images.githubusercontent.com/36626338/39853799-e4a2acba-5441-11e8-9990-f1f5845bbf75.png)

**Comment by Aditi3** [comment]
Hey @manojkraftly, This issue has nothing to do with CleverTap SDK. If you have more questions or concerns you can always reach out to CleverTap support team at support@clevertap.com
