### ISSUE TITLE
CleverTapWatchOS doesn't support if project is written in objective-c 

### ISSUE THREAD

**Issue by shatru-git** [CleverTap/clevertap-ios-sdk#13]
I m trying to embed your framework through pod but getting error for CleverTapWatchOS. My app is written in objective-c. 

This is the error - The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

 I tried to set SWIFT_VERSION manually in build setting but no success. 

![screen shot 2018-07-19 at 5 46 19 pm](https://user-images.githubusercontent.com/344053/42942660-3df80404-8b7e-11e8-99b9-d7ff56e84174.png)

**Comment by Aditi3** [comment]
Hey @shatru-git, 

We have acknowledged the error and in process of migrating the code to Swift3. The fix will be available in next 2 3 days.

Thanks!

**Comment by Aditi3** [comment]
Hey @shatru-git 

To fix the error, In Xcode,  go to your Pods Project > Under the targets, select CleverTapWatchOS > Navigate to the Build Settings > Search Swift Language version > Select the Swift version 

<img width="1014" alt="screen shot" src="https://user-images.githubusercontent.com/11608002/43045334-b804d01c-8dd4-11e8-83d0-9b4b686bb361.png">

Thanks!

**Comment by shatru-git** [comment]
Thanks for quick help. Working fine now
