### ISSUE TITLE
Crashes in CleverTap inboxMessagesDidUpdate

### ISSUE THREAD

**Issue by zhiyao92** [CleverTap/clevertap-ios-sdk#137]
**Describe the bug**
The app crashes on the CleverTap SDK when it loads the notification

**To Reproduce**
Steps to reproduce the behaviour:
1. User 1 load notification
2. Log out
3. User 2 load notification
4. Crash

Wasn't able to reproduce it again. And not able to share project.

**Expected behaviour**
It should not crash

**Screenshots**

This is the crash log from Crashlytics

<img width="1243" alt="CleanShot 2021-07-07 at 14 01 39@2x" src="https://user-images.githubusercontent.com/14795793/124707802-eac07000-df2b-11eb-96a4-a893de72a782.png">
<img width="1253" alt="CleanShot 2021-07-07 at 14 01 49@2x" src="https://user-images.githubusercontent.com/14795793/124707806-ebf19d00-df2b-11eb-9992-5e188c3d0234.png">

**Environment (please complete the following information):**
 - Xcode version: Xcode 12.5.1
 - CleverTap SDK Version: v3.9.3
 - Device: iPhone 11
 - OS: iOS 14.6

**Possible Solution**
SDK team to look into it on their end

**Comment by Aditi3** [comment]
Thank you for filling in the details. Please allow me some time to re-check the same at my end and I will get back to you with an update shortly.

**Comment by Aditi3** [comment]
Hi, @zhiyao92  I tried to repro the issue at my end but have not been able to. Nonetheless, I will add an approximate fix based on the shared stack trace. 

The approximate fix is scheduled to be released soon.

**Comment by zhiyao92** [comment]
Thank you @Aditi3. Look forward to that release.
