### ISSUE TITLE
App Crashed on -[CTLocalDataStore persistLocalProfileIfRequired]

### ISSUE THREAD

**Issue by WaiLynnZaw** [CleverTap/clevertap-ios-sdk#138]
Stack Trace,
Crashed: com.clevertap.serialQueue:8WR-R6R-955Z
0  libobjc.A.dylib                0x1b839add0 objc_release + 16
1  CleverTapSDK                   0x1039f0798 -[CTLocalDataStore persistLocalProfileIfRequired] + 128
2  CleverTapSDK                   0x1039f004c -[CTLocalDataStore setProfileFields:fromUpstream:] + 344
3  CleverTapSDK                   0x1039a4dd0 __25-[CleverTap profilePush:]_block_invoke_2 + 364
4  CleverTapSDK                   0x1039fdcfc +[CTProfileBuilder build:completionHandler:] + 1744
5  CleverTapSDK                   0x1039a4c58 __25-[CleverTap profilePush:]_block_invoke + 92
6  libdispatch.dylib              0x1a34c1a84 _dispatch_call_block_and_release + 32
7  libdispatch.dylib              0x1a34c381c _dispatch_client_callout + 20
8  libdispatch.dylib              0x1a34cb004 _dispatch_lane_serial_drain + 620
9  libdispatch.dylib              0x1a34cbc00 _dispatch_lane_invoke + 404
10 libdispatch.dylib              0x1a34d64bc _dispatch_workloop_worker_thread + 764
11 libsystem_pthread.dylib        0x1ef5527a4 _pthread_wqthread + 276
12 libsystem_pthread.dylib        0x1ef55974c start_wqthread + 8

Currently we don't encounter and not able to produce, but found in the Firebase crash report. SDK version is 3.9.1.

**Comment by Aditi3** [comment]
Hi @WaiLynnZaw 

We have given a rigorous try to this and unable to replicate it. In case we are able to reproduce the same, we would surely get it fixed in the upcoming SDK release.
