### ISSUE TITLE
native display not working

### ISSUE THREAD

**Issue by varunananddudeja** [CleverTap/clevertap-ios-sdk#148]
Native display campaign is not getting called on event trigger. Although event is getting registered in analytics but units callback is not getting called. Calling getUnits() method to get all native units is returning zero counts.

campaign id: 1630983672
clevertap id: Z8W-897-665Z
https://eu1.dashboard.clevertap.com/Z8W-897-665Z/targets/1630983672/show.html

 - Xcode version: [Xcode 12.4]
 - CleverTap SDK Version: [3.9.2]
 - Device: [iPhone xs max]
 - OS: [iOS 14.2]

**Comment by Sonal-Kachare** [comment]
Thank you for reaching out to us. Please allow me some time to re-check the same at my end and I will get back to you with an update shortly.

**Comment by Sonal-Kachare** [comment]
Hi @varunananddudeja 
I tried to reproduce the scenario by creating a sample native display campaign and tested it on the CleverTap’s sample project. I'm able to receive the callback in `func displayUnitsUpdated(_ displayUnits: [CleverTapDisplayUnit])`

[Refer Native Display implementation in iOS](https://developer.clevertap.com/docs/ios#section-setting-native-display-in-i-os)

To further debug the issue you are facing, requesting you to raise support ticket from the dashboard with the Campaign link.

**Comment by Aditi3** [comment]
@varunananddudeja We'd like to follow up with you on this issue. Does it persist? If yes, can you provide us with any other useful information that helps us in debugging further?

**Comment by Sonal-Kachare** [comment]
Hey @varunananddudeja, I am closing this issue due to no response.
