### ISSUE TITLE
OS Version reported as "Others"

### ISSUE THREAD

**Issue by calvarez-ov** [CleverTap/clevertap-ios-sdk#154]
About 26% of ios users events are being being reported with "OS Version" as "Others"

Could this be the same thing as in #47, reported last year?

Could it be that you need to update your database with some ios versions again?

Thanks!

**Comment by Aditi3** [comment]
Hey @calvarez-ov,

yes, this is the same thing and we are working on fixing the aforementioned at our backend. Meanwhile, you can use the event properties of App Launched to track OS Adoption.

**Comment by Aditi3** [comment]
This is fixed at our backend as well. Thank you for your patience.
