### ISSUE TITLE
Never get alert notification with mixed push notification (push silent and alert)

### ISSUE THREAD

**Issue by sawijaya** [CleverTap/clevertap-ios-sdk#161]
Hi Teams,
i have issue, never get alert notification when i used Mixed Push Notifications payload at clevertap.
for the payload like:
`{
    ...
    "aps" :     {
        "alert" :         {
            "body" : "Message goes here 1",
            "title" : "Title goes here 1",
        },
        "content-available" : 1,
        "mutable-content" : 1,
    },
    ...
}`

**Expected**:
- show alert notification (for currently doesnot appear when get notification)
- call method func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) for this method already called.

**Environment**
 - Xcode version: [e.g. Xcode 13.2.x]
 - CleverTap SDK Version: [e.g. v3.10.0]
 - Device: [e.g. iPhoneXR]
 - OS: [e.g. iOS 15.1]

Have any idea for fix this issue?

Thank You.

**Comment by akashvercetti** [comment]
hey @sawijaya We are able to receive push notifications using your sample payload. 
Make sure `Remote notifications` are enabled in the `background modes` inside the capabilities tab of Xcode if you wish to receive pushes in the background.
For push callbacks, I would suggest using the following methods:

- If the app is in foreground:
```
func userNotificationCenter(_ center: UNUserNotificationCenter,
                                willPresent notification: UNNotification,
                                withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void)
```

- If the app is in background:
```
func userNotificationCenter(_ center: UNUserNotificationCenter,
                                didReceive response: UNNotificationResponse,
                                withCompletionHandler completionHandler: @escaping () -> Void)
```

References for creating payload: https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html
