### ISSUE TITLE
Intermittent : Application Crashes during setup

### ISSUE THREAD

**Issue by ankit0812** [CleverTap/clevertap-ios-sdk#164]
```
Crashed: com.clevertap.serialQueue:8WW-Z5W-785Z
0  libobjc.A.dylib                0x2bf0 objc_release + 16
1  CleverTapSDK                   0xba68 -[CleverTap generateAppFields] + 484
2  CleverTapSDK                   0xaff8 -[CleverTap batchHeader] + 64
3  CleverTapSDK                   0x15350 -[CleverTap sendQueue:] + 336
4  CleverTapSDK                   0x1435c -[CleverTap sendQueues] + 92
5  CleverTapSDK                   0x11380 -[CleverTap runSerialAsync:] + 68
6  CleverTapSDK                   0x141f8 -[CleverTap flushQueue] + 172
7  CleverTapSDK                   0x13ef8 -[CleverTap processEvent:withType:] + 2432
8  CleverTapSDK                   0x11380 -[CleverTap runSerialAsync:] + 68
9  CleverTapSDK                   0x13420 -[CleverTap queueEvent:withType:] + 516
10 CleverTapSDK                   0x23c5c -[CleverTap fetchFeatureFlags] + 240
11 libdispatch.dylib              0x2914 _dispatch_call_block_and_release + 32
12 libdispatch.dylib              0x4660 _dispatch_client_callout + 20
13 libdispatch.dylib              0xbde4 _dispatch_lane_serial_drain + 672
14 libdispatch.dylib              0xc958 _dispatch_lane_invoke + 392
15 libdispatch.dylib              0x171a8 _dispatch_workloop_worker_thread + 656
16 libsystem_pthread.dylib        0x10f4 _pthread_wqthread + 288
17 libsystem_pthread.dylib        0xe94 start_wqthread + 8

```

<img width="1376" alt="Screenshot 2022-02-21 at 12 49 05 PM" src="https://user-images.githubusercontent.com/21132111/154907237-b3fd5a26-59f8-4312-bcf0-bb7ea81d4b1d.png">

**Comment by AishwaryaNanna** [comment]
Hi @ankit0812 ,
Please provide following details to help us in investigating the crash ,

**Describe the bug**
A clear and concise description of what the bug is.

**Environment (please complete the following information):**
 - Xcode version: [e.g. Xcode 11.x, Xcode 12.x]
 - CleverTap SDK Version: [e.g. vx.x.x]
 - Device: [e.g. iPhone12, iPhone7]
 - OS: [e.g. iOS 13.3]

**Users affected:**
-How many users affected due to this crash

**Comment by AishwaryaNanna** [comment]
Hi @ankit0812 ,

We are unable to reproduce the crash in our test environment, but 

As I could see that, available RAM on this device is 57.91 MB, because of which OS might be garbage collecting some objects that are being used by the CleverTap-iOS-SDK, hence crashing.

Could you please try running the CleverTap-iOS-SDK on the latest iPhone and check if you face same issue?

**Comment by asifmohd** [comment]
We are seeing a similar crash for our app in the `generateAppFields` method

<img width="488" alt="image" src="https://user-images.githubusercontent.com/4892875/158945550-76a8489a-087e-41f1-ae6f-7396ce17fda7.png">

We are using clevertap SDK version 3.10.0.

Looking at the [mentioned line number](https://github.com/CleverTap/clevertap-ios-sdk/blob/3.10.0/CleverTapSDK/CleverTap.m#L1096) in the crash log, it seems to be crashing when accessing `self.deviceInfo.model`

In the implementation of `self.deviceInfo.model` I noticed that we are making the `uname` system call.

[The docs](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/uname.3.html) for `uname` mentions that it returns a non zero exit code in case of errors and it looks like it's not being handled in the clevertap codebase. [Link to implementation](https://github.com/CleverTap/clevertap-ios-sdk/blob/3.10.0/CleverTapSDK/CTDeviceInfo.m#L140-L144)

Looking on the internet for Google's implementation of similar functionality, we can see [that they are initialising](https://github.com/google/GoogleUtilities/blob/8c4fcf6af37be29975372f38e5dd60c2d1ab47c1/GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.m#L236-L239) an NSString only if uname returns 0.

While I haven't been able to recreate this crash as well, I think shipping a similar fix, could help resolve these crashes in clevertap SDK.

**Comment by akashvercetti** [comment]
@asifmohd An excellent point Asif. We have added it to the list of hot-fixes in the next upcoming release.

**Comment by akashvercetti** [comment]
We have added a possible fix as highlighted by @asifmohd in our latest release 4.0.1. Please update to it
