### ISSUE TITLE
Application crashes randomly during SDK setup 

### ISSUE THREAD

**Issue by viviamezquita18** [CleverTap/clevertap-ios-sdk#165]
Hi, some of my users (`117`) are not being able to open the application due to an error related to CleverTap at the time of initialization, the error occurs for no apparent reason and does not always occur.

```
Application Specific Information:
inNotificationQueue > objectAtIndexedSubscript: > storageKeyWithSuffix: >
Attempted to dereference garbage pointer 0x54.

Application Crashed:
0   libdispatch.dylib               0x30116b0d4         dispatch_async
1   libdispatch.dylib               0x30116b04c         dispatch_async
2   CleverTapSDK                    0x1065bc908         -[CleverTap runOnNotificationQueue:]
3   CleverTapSDK                    0x1065c3750         -[CleverTap parseResponse:]
4   CleverTapSDK                    0x1065c2a94         -[CleverTap sendQueue:]
5   CleverTapSDK                    0x1065c15b0         -[CleverTap sendQueues]
6   libdispatch.dylib               0x301164920         _dispatch_call_block_and_release
7   libdispatch.dylib               0x30116666c         _dispatch_client_callout
8   libdispatch.dylib               0x30116ddf0         _dispatch_lane_serial_drain
9   libdispatch.dylib               0x30116e964         _dispatch_lane_invoke
10  libdispatch.dylib               0x3011791b4         _dispatch_workloop_worker_thread
11  libsystem_pthread.dylib         0x3e2da90f0         _pthread_wqthread
```

This error has occurred on several devices, so far we have been able to identify those with the following characteristics:
 - Xcode version:  `Xcode 13.2`
 - CleverTap SDK Version: `3.9.4`
 - Device: iPhone [`XR`, `11`, `12`]
 - OS: iOS [`14`, `15`]

Debugging the application I found that the error is appearing at [this line](https://github.com/CleverTap/clevertap-ios-sdk/blob/e788bca97282cd7c4bee2d1446559c516e133c60/CleverTapSDK/CleverTap.m#L1833) of the CleverTap method file.

**Comment by AishwaryaNanna** [comment]
Hi @viviamezquita18 ,

Based on the App Specific info **Attempted to dereference garbage pointer** , I believe that you are experiencing heap corruption. These kind of crashes can be really hard to debug.

Heap corruption, which is a specific case of a memory corruption, can be hard to track down. The main reason is the source of the corruption is usually not captured at all by the stack trace.

It’s totally possible, and common, for an unrelated system to just overwrite a bit of memory CleverTap uses.

We were not able to reproduce this in our test environments. But we will keep an eye on such issues in the future.

**Comment by viviamezquita18** [comment]
The solution and reason we found for this crash was that Clevertap has this bug only with the new SwiftUI life cycle (AppMain), so we had to add AppDelegate file to prevent this to happen.
