### ISSUE TITLE
[CTInboxController _save] + 211

### ISSUE THREAD

**Issue by litongde** [CleverTap/clevertap-ios-sdk#166]
**Describe the bug**
Problems detected by firebase.

**To Reproduce**
Steps to reproduce the behaviour:
4. See an error

This could be a description, debug logs/console output, etc. You can also share a demo project with us where the issue is reproducible.

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/10285641/156959905-4c1e2261-0b30-402b-8961-211c8418d698.png)

Crashed: NSManagedObjectContext 0x280884ea0
0  libobjc.A.dylib                0x3a58 object_getClass + 48
1  CoreData                       0x707f0 _PFObjectIDFastHash64 + 32
2  CoreFoundation                 0xf004 __CFBasicHashRehash + 948
3  CoreFoundation                 0xe81c CFBasicHashRemoveValue + 2412
4  CoreFoundation                 0x45d90 CFDictionaryRemoveValue + 336
5  CoreData                       0x108994 -[NSManagedObjectContext(_NSInternalAdditions) _forgetObject:propagateToObjectStore:removeFromRegistry:] + 132
6  CoreData                       0x52bc4 -[NSManagedObjectContext _didSaveChanges] + 3216
7  CoreData                       0x2efc0 -[NSManagedObjectContext save:] + 3656
8  CleverTapSDK                   0x4e18c -[CTInboxController _save] + 211 (CTInboxController.m:211)
9  CleverTapSDK                   0x4e060 __37-[CTInboxController _deleteMessages:]_block_invoke + 199 (CTInboxController.m:199)
10 CoreData                       0x200b4 developerSubmittedBlockToNSManagedObjectContextPerform + 156
11 libdispatch.dylib              0x4670 _dispatch_client_callout + 20
12 libdispatch.dylib              0xbdf4 _dispatch_lane_serial_drain + 672
13 libdispatch.dylib              0xc968 _dispatch_lane_invoke + 392
14 libdispatch.dylib              0x171b8 _dispatch_workloop_worker_thread + 656
15 libsystem_pthread.dylib        0x10f4 _pthread_wqthread + 288
16 libsystem_pthread.dylib        0xe94 start_wqthread + 8

**Environment (please complete the following information):**
 - CleverTap SDK Version: 3.10.0

**Comment by akashvercetti** [comment]
Hi, We were not able to reproduce this issue. Could you try describing a possible scenario when this inbox related crash might happen?

**Comment by litongde** [comment]
> Hi, We were not able to reproduce this issue. Could you try describing a possible scenario when this inbox related crash might happen?

![image](https://user-images.githubusercontent.com/10285641/184058333-972cdae7-bbf6-4ec0-a95a-d208cc350afc.png)

You are advised to use ios15 for replication, mainly on ios15 devices. It also exists in the latest Clevertap SDK 4.1.1

**Comment by akashvercetti** [comment]
@litongde we have implemented some possible fixes for the inbox issue and would be releasing them along with iOS 16 support tomorrow. 👍

**Comment by akashvercetti** [comment]
@litongde we have released a new version v4.1.2 with possible inbox fixes. Please update to the latest version and see if it works out.
