### ISSUE TITLE
Demerge user profile

### ISSUE THREAD

**Issue by gupta150891** [CleverTap/clevertap-ios-sdk#167]
Due to some issues at our end in understanding the use of custom clevertap id, now our all users are adding to the same profile.

We rectify the issue but to demerge all the users from same profile so that the events don't get lost we are using demerge profile api but its not working.
Link: [https://developer.clevertap.com/docs/demerge-user-profile-api](https://developer.clevertap.com/docs/demerge-user-profile-api)

Url: https://sg1.api.clevertap.com/1/demerge/profiles.json
json: {"identities": ["107758"]}

I am getting success from the api but on Dashboard profile is not demerged.
Can anyone help in this?

**Comment by darshanclevertap** [comment]
@gupta150891 I'd suggest you raise a support ticket for this from the Dashboard. Our customer success team will be able to help you out better in this case.
