### ISSUE TITLE
The events name will automatic to change to hump format.

### ISSUE THREAD

**Issue by PacoPacoPakitor** [CleverTap/clevertap-ios-sdk#169]
In swift i have integration the latest version clevertap sdk, when i sent the event name with lowercase, but i checked from console.It's change to uppercase automatically. for example: 
     I sent:  CleverTap.sharedInstance()?.recordEvent("login_mobile", withProps: para)
     I got:  LoginMobile(From clevertap console)
Can you help to check this?

**Comment by akashvercetti** [comment]
@PacoPacoPakitor We have verified it on our end and found that the event name goes as it is. Please look at the screenshots of the console and the CleverTap Dashboard. Could you try updating to the latest SDK version 4.0.0 if you haven't already?.

<img width="1063" alt="Screenshot 2022-03-17 at 10 43 03 AM" src="https://user-images.githubusercontent.com/11962399/158741793-7d12de13-b507-422a-9d4c-4bf5805d3f17.png">

<img width="704" alt="Screenshot 2022-03-17 at 10 42 45 AM" src="https://user-images.githubusercontent.com/11962399/158741786-c59461f1-fca8-47d2-9a3d-58be62b145ad.png">
