### ISSUE TITLE
HTTP load failed

### ISSUE THREAD

**Issue by lintocj** [CleverTap/clevertap-ios-sdk#17]
When I trying to push data to cleverTap I am getting HTTP load failed and that data is not passing to clever tap dashboard as well.

Task <F992BA6D-5821-4397-BF83-09841966A6A9>.<7> HTTP load failed (error code: -1003 [12:8])

Task <F992BA6D-5821-4397-BF83-09841966A6A9>.<7> finished with error - code: -1003

**Comment by Aditi3** [comment]
Hey @lintocj 

To help you better, I would request you enable debug logs in your application and email us on support@clevertap.com.

Helping link to enable debug logs: https://developer.clevertap.com/docs/ios#section-debugging

**Comment by Aditi3** [comment]
Hey @lintocj 

Could you verify the CleverTap credentials once? Check the values of the CleverTapAccountID and CleverTapToken in your Info.Plist.

Basically, when you add incorrect values for CleverTap credentials, in that case, will get this error.

**Comment by lintocj** [comment]
Okay! it started working after changing the device.

**Comment by Aditi3** [comment]
Glad it worked for you. Closing it, feel free to reopen if you need further help or you can also write to support@clevertap.com.
