### ISSUE TITLE
Multiple different crashes when the sharedInstance is accessed across different threads at app launch.

### ISSUE THREAD

**Issue by asifmohd** [CleverTap/clevertap-ios-sdk#175]
**Describe the bug**

The app crashes when we try to access `Clevertap.sharedInstance()` from multiple threads at app launch.

We are seeing > 1000 crashes per day for our app because of this.

There are many more other crashes related to Clevertap in our crash reporting tool, which could be resolved if we resolve this issue I believe.

**To Reproduce**

Steps to reproduce the behaviour:
1. Clone [this repository](https://github.com/asifmohd/cleverTapTest)
2. Run pod install to install the latest ClevertapSDK
3. Build and run the app on a simulator
4. Across 5 consecutive launches, you should see a crash at least once, sometimes in all 5 launches
5. Increase/decrease the number of accesses to `Clevertap.sharedInstance()` in appDidFinishLaunching to increase/decrease the chances of a crash occurring accordingly.

**Expected behaviour**

The crash should not occur

**Screenshots**

Memory leaks

<img width="1307" alt="memory leak 1 screenshot" src="https://user-images.githubusercontent.com/4892875/167149965-36c4d0f6-1b7b-4b6a-b135-19af329c6409.png">

<img width="1307" alt="memory leak 2 screenshot" src="https://user-images.githubusercontent.com/4892875/167150022-69c7737e-a5c4-43a1-abcf-a020f4bfb183.png">

Example crash:

<img width="1512" alt="crash screenshot" src="https://user-images.githubusercontent.com/4892875/167152929-ea18d0ec-6dc7-4c45-a63a-9d74320c903d.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/4892875/167154023-34a84188-f643-48ba-987b-c3ea28248f66.png">

**Environment (please complete the following information):**

 - Xcode version: Xcode 13.3.1
 - CleverTap SDK Version: 4.0.1
 - Device: iPhone 8 simulator
 - OS: iOS 15.4

**Possible Solution**

`sharedInstance` Singleton should be created only once. For every subsequent call to the sharedInstance, we should make the caller wait until the entire initial Clevertap init finishes successfully.

**Additional context**

In my testing I observed 3-4 different kinds of crashes with the same sample code in the attached github repo.

**Comment by akashvercetti** [comment]
Alright @asifmohd let us view the repo you've provided and come back to you with a possible solution. 👍

**Comment by akashvercetti** [comment]
@asifmohd we have added a possible fix for this on our feature branch at https://github.com/CleverTap/clevertap-ios-sdk/tree/task/SDK-1618-shared-instance-thread-safe . Could you please test it with the sample app repo provided by you at https://github.com/asifmohd/cleverTapTest before we push it to release? Here's a Podfile sample just in case:

`target 'ClevertapTest' do
  pod 'CleverTap-iOS-SDK', :git => 'https://github.com/CleverTap/clevertap-ios-sdk.git', :branch => 'task/SDK-1618-shared-instance-thread-safe', :modular_headers => true
end`

**Comment by asifmohd** [comment]
Tested it out on the repo, with upto 1000 loops, and did not observe any crashes and no more duplicate/leaked instances in memory graph.

Looks like the issue should be fixed ❤️

**Comment by akashvercetti** [comment]
We have added a fix for this in our latest release for v4.1.0 https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/4.1.0
