### ISSUE TITLE
autoIntegrate for SwiftUI projects

### ISSUE THREAD

**Issue by denizdogan** [CleverTap/clevertap-ios-sdk#176]
As far as I can tell, this library doesn't support SwiftUI apps, and that's because `getSharedApplication` will always return `nil`, unless I'm mistaken?

I think this will always be `nil` for SwiftUI apps: `[UIApplication performSelector:@selector(sharedApplication)]`

Is there any way you can make `autoIntegrate` work nicely on SwiftUI projects? The docs are rather vague saying that `autoIntegrate` will "just work", but there's clearly numerous pitfalls to take into consideration.

**Comment by akashvercetti** [comment]
@denizdogan We have added it to the release pipeline and will be looking into adding SwiftUI support in the future. In the meantime, could you try manually adding an AppDelegate class like so: 
https://www.hackingwithswift.com/quick-start/swiftui/how-to-add-an-appdelegate-to-a-swiftui-app

https://github.com/CleverTap/clevertap-ios-sdk/issues/165#issuecomment-1103247860

**Comment by akashvercetti** [comment]
We have updated the documentation for adding the `AppDelegate` to make `autoIntegrate` work with SwiftUI. 
https://developer.clevertap.com/docs/advanced-options-ios#swiftui-support
