### ISSUE TITLE
[CTInboxController _messageForId:] + 188

### ISSUE THREAD

**Issue by litongde** [CleverTap/clevertap-ios-sdk#177]
![image](https://user-images.githubusercontent.com/10285641/170622739-4ff172c1-ad88-4ee3-ab75-da3fb3f7bb05.png)

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x8a44 object_isClass + 16
1  Foundation                     0x63b34 -[NSFunctionExpression expressionValueWithObject:context:] + 572
2  Foundation                     0x4d7ec -[NSComparisonPredicate evaluateWithObject:substitutionVariables:] + 216
3  Foundation                     0x6ab70 _filterObjectsUsingPredicate + 268
4  Foundation                     0xbb644 -[NSOrderedSet(NSPredicateSupport) filteredOrderedSetUsingPredicate:] + 212
5  CleverTapSDK                   0x4df9c -[CTInboxController _messageForId:] + 188 (CTInboxController.m:188)
6  CleverTapSDK                   0x4d684 -[CTInboxController messageForId:] + 116 (CTInboxController.m:116)
7  CleverTapSDK                   0x1e398 -[CleverTap getInboxMessageForId:] + 4200 (CleverTap.m:4200)
8  CleverTapSDK                   0x1e568 -[CleverTap recordInboxNotificationViewedEventForID:] + 4219 (CleverTap.m:4219)
9  eWallet-iOS                    0xfe937c +[TNGCleverTapHandle recordInboxMessageVisibleForID:] + 1856548
10 eWallet-iOS                    0xfe9100 +[TNGCleverTapHandle getAllInboxMessages] + 1855912
11 eWallet-iOS                    0xfe8e9c __50+[TNGCleverTapHandle initializeInboxWithCallback:]_block_invoke + 1855300
12 CleverTapSDK                   0x1dd64 __41-[CleverTap initializeInboxWithCallback:]_block_invoke.1851 + 4145 (CleverTap.m:4145)
13 libdispatch.dylib              0x3a2c _dispatch_client_callout + 20
14 libdispatch.dylib              0x12d68 _dispatch_async_and_wait_invoke + 92
15 libdispatch.dylib              0x3a2c _dispatch_client_callout + 20
16 libdispatch.dylib              0x11f48 _dispatch_main_queue_drain + 928
17 libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF + 44
18 CoreFoundation                 0x522f0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
19 CoreFoundation                 0xc1f4 __CFRunLoopRun + 2532
20 CoreFoundation                 0x1f6b8 CFRunLoopRunSpecific + 600
21 GraphicsServices               0x1374 GSEventRunModal + 164
22 UIKitCore                      0x513e88 -[UIApplication _run] + 1100
23 UIKitCore                      0x2955ec UIApplicationMain + 364
24 eWallet-iOS                    0x104230 main + 23 (main.m:23)
25 ???                            0x106b09ce4 (缺少)

**Comment by akashvercetti** [comment]
Hi, We are looking into improving the Inbox related code and fixing related bugs. We'll let you know as soon as the fixes are released.

**Comment by litongde** [comment]
> Hi, We are looking into improving the Inbox related code and fixing related bugs. We'll let you know as soon as the fixes are released.

![image](https://user-images.githubusercontent.com/10285641/184269224-76438799-b797-47a6-93d6-ba769bfeb1b4.png)

This issue remains with Clevertap SDK 4.1.1

**Comment by akashvercetti** [comment]
@litongde we have implemented some possible fixes for the inbox issue and would be releasing them along with iOS 16 support tomorrow. 👍

**Comment by akashvercetti** [comment]
@litongde we have released a new version v4.1.2 with possible inbox fixes. Please update to the latest version and see if it works out.
