### ISSUE TITLE
'Deep link / External URL' couldn't let app navigate to desired path

### ISSUE THREAD

**Issue by g212gs** [CleverTap/clevertap-ios-sdk#178]
A specified URL in `Deep link / External URL` is not opening the desired path or even let the user move to safari or default web-browser

**To Reproduce**
1. Go to CleverTap dashboard
2. Send push notifications to any user, do the campaign for sending push notification
3. Set the required http(s) url in `Deep link / External URL` section e.g. https://mydomain.com/profile or https://subdomain.onelink.me/<CUSTOM_ID>/<PATH_ID>
4. When the user tap on such kind of notification - it opens the app and suddenly moves to safari or default web browser.

**Expected behavior**
It should give us control to handle the navigation for the deep link URL and keep it in the application only.

**Screenshots**
[How to set Deep link / External URL](https://www.linkpicture.com/q/Screenshot-2022-05-30-at-7.29.10-PM.png)

**Environment (please complete the following information):**
 - Xcode version: 13.2.1
 - CleverTap SDK Version: latest i.e. using SPM
 - Device: iPhone 11
 - OS: iOS 15.4.1

**Possible Solution**
Don't know 

**Information as per document:**

> Deep Link/External URL - (Reference URL: https://developer.clevertap.com/docs/ios#section-push-notifications)
> Deep links allow you to land the user to a particular part of your app. Your app’s OpenURL method is called with the deep link specified here. If you wish to use external URLs, then you will have to whitelist the IPs or provide http/https before the URL so that they can be handled properly by the SDK

**Additional context**
If we set the `Custom key-value pairs` then it will open the app and we can handle the navigation, but it looks like a hack.

**Comment by akashvercetti** [comment]
@g212gs We do have a protocol which lets you handle push/In-App/Inbox notification URLs. Here it is: https://developer.clevertap.com/docs/ios#custom-handling-deeplink
Do check it out and let us know if it fits.

**Comment by g212gs** [comment]
[akashvercetti](https://github.com/akashvercetti) - Using the above method, I could handle the URL in `Deep link / External URL`.

Thank you very much.

Problem solved 🤝
