### ISSUE TITLE
+[CTPreferences getIntForKey:withResetValue:]

### ISSUE THREAD

**Issue by litongde** [CleverTap/clevertap-ios-sdk#185]
![image](https://user-images.githubusercontent.com/10285641/174510773-2f3a9d6d-3da6-4099-a732-773b438c7d53.png)

Crashed: com.clevertap.serialQueue:R99-RK5-875Z
0  libsystem_malloc.dylib         0x52cc tiny_free_list_add_ptr + 128
1  libsystem_malloc.dylib         0x379c tiny_malloc_from_free_list + 1648
2  libsystem_malloc.dylib         0x3c84 tiny_malloc_should_clear + 220
3  libsystem_malloc.dylib         0x6e24 szone_malloc_should_clear + 80
4  libsystem_malloc.dylib         0x4e5c _malloc_zone_calloc + 88
5  CoreFoundation                 0x6a798 mdict_rehashd + 88
6  CoreFoundation                 0xf3f0 -[__NSDictionaryM __setObject:forKey:] + 900
7  CoreFoundation                 0x49b2c -[__NSFrozenDictionaryM __apply:context:] + 128
8  CoreFoundation                 0xf1858 -[CFPrefsSource mergeIntoDictionary:sourceDictionary:cloudKeyEvaluator:] + 176
9  CoreFoundation                 0x358cc -[CFPrefsSearchListSource alreadylocked_getDictionary:] + 756
10 CoreFoundation                 0x96774 -[CFPrefsSearchListSource alreadylocked_copyValueForKey:] + 172
11 CoreFoundation                 0xfdd18 -[CFPrefsSource copyValueForKey:] + 60
12 CoreFoundation                 0x37838 __76-[_CFXPreferences copyAppValueForKey:identifier:container:configurationURL:]_block_invoke + 44
13 CoreFoundation                 0x56d24 __108-[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:]_block_invoke + 400
14 CoreFoundation                 0x2ebd4 normalizeQuintuplet + 356
15 CoreFoundation                 0x27cc8 -[_CFXPreferences withSearchListForIdentifier:container:cloudConfigurationURL:perform:] + 152
16 CoreFoundation                 0x85f80 -[_CFXPreferences copyAppValueForKey:identifier:container:configurationURL:] + 168
17 CoreFoundation                 0x4c04c _CFPreferencesCopyAppValueWithContainerAndConfiguration + 128
18 Foundation                     0x25a38 -[NSUserDefaults(NSUserDefaults) objectForKey:] + 76
19 CleverTapSDK                   0x58ab4 +[CTPreferences getIntForKey:withResetValue:] + 11 (CTPreferences.m:11)
20 CleverTapSDK                   0x56b10 -[CTLocalDataStore getLastDataSyncTimeWithResetValue:] + 700 (CTLocalDataStore.m:700)
21 CleverTapSDK                   0x5390c -[CTLocalDataStore addDataSyncFlag:] + 115 (CTLocalDataStore.m:115)
22 CleverTapSDK                   0x13e14 -[CleverTap processEvent:withType:] + 2535 (CleverTap.m:2535)
23 CleverTapSDK                   0x11540 -[CleverTap runSerialAsync:] + 2058 (CleverTap.m:2058)
24 CleverTapSDK                   0x135f4 -[CleverTap queueEvent:withType:] + 2460 (CleverTap.m:2460)
25 CleverTapSDK                   0x20d98 __47-[CleverTap recordDisplayUnitViewedEventForID:]_block_invoke_2 + 4571 (CleverTap.m:4571)
26 CleverTapSDK                   0x3a7cc +[CTEventBuilder buildDisplayViewStateEvent:forDisplayUnit:andQueryParameters:completionHandler:] + 394 (CTEventBuilder.m:394)
27 CleverTapSDK                   0x20ce4 __47-[CleverTap recordDisplayUnitViewedEventForID:]_block_invoke + 4575 (CleverTap.m:4575)
28 libdispatch.dylib              0x1e6c _dispatch_call_block_and_release + 32
29 libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
30 libdispatch.dylib              0xb124 _dispatch_lane_serial_drain + 668
31 libdispatch.dylib              0xbc80 _dispatch_lane_invoke + 392
32 libdispatch.dylib              0x16500 _dispatch_workloop_worker_thread + 648
33 libsystem_pthread.dylib        0x10bc _pthread_wqthread + 288
34 libsystem_pthread.dylib        0xe5c start_wqthread + 8

**Comment by akashvercetti** [comment]
Hi, We have included a few possible crash fixes in our latest release v.4.1.0 . Could you please update to the latest version and have a go? https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/4.1.0

**Comment by litongde** [comment]
> 

Ok, thank you
