### ISSUE TITLE
-[_NSFaultingMutableOrderedSet willReadWithContents:]

### ISSUE THREAD

**Issue by litongde** [CleverTap/clevertap-ios-sdk#186]
CoreData

![image](https://user-images.githubusercontent.com/10285641/174510949-483a8118-53da-4b4d-861f-bb773aa7c1ea.png)

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x39d0 objc_retain + 16
1  CoreData                       0xe7d8c -[_NSFaultingMutableOrderedSet willReadWithContents:] + 576
2  CoreData                       0xe8fc4 -[_NSFaultingMutableOrderedSet containsObject:] + 36
3  CoreData                       0x4be4c -[NSManagedObject _maintainInverseRelationship:forProperty:oldDestination:newDestination:] + 1380
4  CoreData                       0x3d83c -[NSManagedObject(_NSInternalMethods) _didChangeValue:forRelationship:named:withInverse:] + 548
5  Foundation                     0x32a6c NSKeyValueNotifyObserver + 292
6  Foundation                     0x1e604 NSKeyValueDidChange + 376
7  Foundation                     0x58548 NSKeyValueDidChangeWithPerThreadPendingNotifications + 160
8  CoreData                       0x90714 -[NSManagedObject didChangeValueForKey:] + 124
9  CoreData                       0x3fb28 -[NSManagedObject _updateFromRefreshSnapshot:includingTransients:] + 696
10 CoreData                       0x1a894c -[NSManagedObjectContext _copyChildObject:toParentObject:fromChildContext:] + 228
11 CoreData                       0x1a8ed4 -[NSManagedObjectContext _parentProcessSaveRequest:inContext:error:] + 676
12 CoreData                       0x1a9768 __82-[NSManagedObjectContext(_NestedContextSupport) executeRequest:withContext:error:]_block_invoke + 576
13 CoreData                       0x1ac104 internalBlockToNSManagedObjectContextPerform + 100
14 libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
15 libdispatch.dylib              0x12d68 _dispatch_async_and_wait_invoke + 92
16 libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
17 libdispatch.dylib              0x11f48 _dispatch_main_queue_drain + 928
18 libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF + 44
19 CoreFoundation                 0x51800 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
20 CoreFoundation                 0xb704 __CFRunLoopRun + 2532
21 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
22 GraphicsServices               0x1374 GSEventRunModal + 164
23 UIKitCore                      0x514648 -[UIApplication _run] + 1100
24 UIKitCore                      0x295d90 UIApplicationMain + 364
25 eWallet-iOS                    0x10b388 main + 23 (main.m:23)
26 ???                            0x104f21ce4 (缺少)

**Comment by akashvercetti** [comment]
Hi, We are currently looking into improving the Inbox related code and fixing related bugs. We'll let you know as soon as the fixes are released.
