### ISSUE TITLE
CTInboxController.m line 162  -[CTInboxController unreadMessages]

### ISSUE THREAD

**Issue by litongde** [CleverTap/clevertap-ios-sdk#193]
CleverTap SDK Version: 4.1.1

**Comment by litongde** [comment]
![image](https://user-images.githubusercontent.com/10285641/184589456-8b343686-2902-461e-98f2-4766a5a0acfc.png)

**Comment by akashvercetti** [comment]
@litongde alright let us research some more and try to debug/replicate this issue 👍

**Comment by akashvercetti** [comment]
@litongde we have implemented some possible fixes for the inbox issue and would be releasing them along with iOS 16 support tomorrow. 👍

**Comment by akashvercetti** [comment]
@litongde we have released a new version v4.1.2 with possible inbox fixes. Please update to the latest version and see if it works out.
