### ISSUE TITLE
Could not cast value of type 'CleverTapAppDelegateSurrogate'

### ISSUE THREAD

**Issue by alvinvarghese** [CleverTap/clevertap-ios-sdk#2]
Just integrated CleverTap in my app. Completed these steps. [ I am not using the Test version of my app ]

1. Installed pod **'pod 'CleverTap-iOS-SDK''**
2. Added keys in info.plist, **CleverTapToken** & **CleverTapAccountID**
3. Imported framework in bridging header file
4. Added **"CleverTap.autoIntegrate()"** code in **"didFinishLaunchingWithOptions"**

While running the project it crashes the app, by saying this error ->

```
2016-04-07 11:30:57.481 MyApp[32989:1568193] [Crashlytics] Version 3.7.0 (102)
Could not cast value of type 'CleverTapAppDelegateSurrogate' (0x106ba73d0) to 'MyApp.AppDelegate' (0x106ba6a18).
```

And i got error in this line? Whats wrong with this line? isn't it the default way to do this?

```
let appDelegate = UIApplication.sharedApplication().delegate as! AppDelegate
```

Looking forward to your reply.

**Comment by alvinvarghese** [comment]
My **didFinishLaunchingWithOptions** method in App Delegate was looking like this.

```
    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool
 {
        // BetterHQ
        NFNFeedBackSdk.sharedInstance.initializeSDK("NQ3AZEATNEXT113")
        
        // Uber Ride
        RidesClient.sharedInstance.configureClientID(API_KEY.Uber_Client_ID.rawValue)
        
        // Google Maps Services
        GMSServices.provideAPIKey(API_KEY.GoogleAPIKey.rawValue)
        
        // Fabirc
        Fabric.with([Crashlytics.self])

        // Clever Tap
        CleverTap.autoIntegrate()
        
        return true
    }

```

And the app crashed, Then i have changed it to like this.

```
    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool
 {
        // Clever Tap
        CleverTap.autoIntegrate()
        
        // BetterHQ
        NFNFeedBackSdk.sharedInstance.initializeSDK("NQ3AZEATNEXT113")
        
        // Uber Ride
        RidesClient.sharedInstance.configureClientID(API_KEY.Uber_Client_ID.rawValue)
        
        // Google Maps Services
        GMSServices.provideAPIKey(API_KEY.GoogleAPIKey.rawValue)
        
        // Fabirc
        Fabric.with([Crashlytics.self])

        return true
    }

```
Then it worked fine, I need a better explanation on this, #Curiosity

**Comment by pwilkniss** [comment]
@alvinvarghese   autoIntegrate is a convenience method that lets our SDK automatically detect that your app has launched, handle device token registration, push notifications, in-app notifications and url referrer tracking, and set up a singleton instance of the CleverTap class.

We do that by proxying the app delegate via a surrogate object, and then passing delegate messages to your app delegate as well as our SDK.
see more in our docs here  https://support.clevertap.com/integration/ios-sdk/#auto-integration

As such, Swift doesn't like the cast back to your AppDelegate class:  let appDelegate = UIApplication.sharedApplication().delegate as! AppDelegate;  

you could do this:  let appDelegate = UIApplication.sharedApplication().delegate;

but if you have custom things you need to access in your app delegate, then you can remove the autoIntegrate call and use our manual integration instead.   Basically, its just adding a few calls to the CleverTap SDK in your app delegate methods.
see here https://support.clevertap.com/integration/ios-sdk/#manual-integration

**Comment by iosdeveloper480** [comment]
Could not cast value of type 'CleverTapAppDelegateSurrogate' (0x100734148) to 'MyApp.AppDelegate' (0x10072fd50).

After integrating CleverTap in AppDelegate.. When i call this one in any class 
let appDelegate = UIApplication.sharedApplication().delegate as! AppDelegate

Then the about Error shows in console and App Crashed.........

Please anyone help me... Whats i am doing wrong.

**Comment by alvinvarghese** [comment]
@iosdeveloper480  Just try this, 

[let appDelegate = UIApplication.sharedApplication().delegate](url)

**Comment by sanjeev777** [comment]
In swift 3 sharedApplication() is no present so we can't write sharedApplication().delegate

**Comment by pwilkniss** [comment]
@sanjeev777   see  https://github.com/CleverTap/clevertap-ios-sdk/issues/2#issuecomment-206969332

if you have custom things you need to access in your app delegate, then you can remove the autoIntegrate call and use our manual integration instead. Basically, its just adding a few calls to the CleverTap SDK in your app delegate methods.
see here https://support.clevertap.com/integration/ios-sdk/#manual-integration

**Comment by iamsanketray123** [comment]
I did not do the manual installation. I just removed the line `CleverTap.autoIntegrate()` and it fixed my crash.  What am I going to miss, if I dont complete the manual installation?

**Comment by Aditi3** [comment]
Hey @iamsanketray123 

To use the CleverTap iOS SDK, you have two options. You can integrate with a single of code, the **autoIntegrate** method lets you automatically track app launches, receive in-app notifications, and enable deep-link tracking or, you can **manually** turn on different CleverTap SDK features. 

The manual integration steps are documented here: https://developer.clevertap.com/docs/ios#section-push-notifications
