### ISSUE TITLE
CTLocalDataStore.m line 635 

### ISSUE THREAD

**Issue by litongde** [CleverTap/clevertap-ios-sdk#204]
![image](https://user-images.githubusercontent.com/10285641/197111142-a6e6c298-de11-44d6-8a78-f941a8e7a0f5.png)

**Comment by litongde** [comment]
CleverTap SDK version：4.1.2
iOS version：iOS16 / iOS15
Dependency manager used：Cocoapods

**Comment by litongde** [comment]
This problem is the most urgent, and there are a lot of flashbacks. And from the flash back point of view mainly exists in multithreaded calls.

I can provide more trace information about possible calls here, and work hard together to fix the problem.

Now when I was in the app start will initialize clevertap inbox call as shown in figure initializeInboxWithCallback, and made a series of operations, I screenshots, to see if there are helpful to the problem. As follows:

![image](https://user-images.githubusercontent.com/10285641/197133500-579ef351-745d-41d8-ab4e-93e06b8c92e4.png)

**Comment by akashvercetti** [comment]
@litongde We have released an update last week specifically for the class and method mentioned in your stack trace. The latest version is v4.1.3. Could you try updating it to the latest version and checking if it helps?
Also, Would it be possible for you to create a barebones sample empty app/repository with just your inbox initialising/callback implementing code so we could debug it out ourselves?
The latest release v4.1.3: https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/4.1.3

**Comment by litongde** [comment]
> 

Thank you for your reply. I will update it to the latest SDK and try again. As for the empty inbox sample program you mentioned, it is difficult to reproduce this flash back in our local area. We still need to give you the specific flash back from firebase, code analysis, and possible data burying points that we need to do. To do a sweep. From the flash back, the larger may be due to multi-thread security call issues and memory leaks. I'm working on it, too, if there's anything you need from me. Let me know and I'll be the first to cooperate. thank you
