### ISSUE TITLE
Error on adding Clevertap as SPM on Apple TV

### ISSUE THREAD

**Issue by gauravvig** [CleverTap/clevertap-ios-sdk#214]
Getting following error on adding Clevertap SDK as SPM in Apple TV target.

/SourcePackages/checkouts/clevertap-ios-sdk/CleverTapSDK/Inbox/resources/CTCarouselMessageCell~land.xib: iOS xibs do not support target device type "tv".

**Comment by AishwaryaNanna** [comment]
Hi @gauravvig ,
We don’t support tvOS as of now,
however we have noted this for our future development

Thanks
