### ISSUE TITLE
SDWebImage is downgraded

### ISSUE THREAD

**Issue by ngochai84** [CleverTap/clevertap-ios-sdk#219]
As i used CleverTap iOS SDK 4.1.3, I can use latest SDWebImage 5.14.x, but if I upgrade CleverTap iOS SDK to 4.1.6, it required for SDWebimage 5.11.1, Why is it?

below is my log from pod install error
```

[!] CocoaPods could not find compatible versions for pod "SDWebImage":
  In snapshot (Podfile.lock):
    SDWebImage (= 5.14.2, ~> 5.1, ~> 5.14)

  In Podfile:
    CleverTap-iOS-SDK (= 4.1.6) was resolved to 4.1.6, which depends on
      SDWebImage (~> 5.11.1)

    SDWebImage (~> 5.14.2)

Specs satisfying the `SDWebImage (~> 5.14.2), SDWebImage (= 5.14.2, ~> 5.1, ~> 5.14), SDWebImage (~> 5.11.1)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by mrazam110** [comment]
I am facing the similar issue! Any fixes?

**Comment by akashvercetti** [comment]
Hi. We have updated the `SDWebImage` dependency in our latest release v4.2.0: https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/4.2.0
