### ISSUE TITLE
Carthage builds failing - FLAnimatedImage

### ISSUE THREAD

**Issue by codeOfRobin** [CleverTap/clevertap-ios-sdk#22]
Hey folks! 👋 

It looks like Carthage installs are failing:
`dyld: Library not loaded: @rpath/FLAnimatedImage.framework/FLAnimatedImage`

AFAICT, It looks like you're using `FLAnimatedImage` and `SDWebImage` as dependencies but haven't added them to your Cartfile (or have a cartfile, for that matter). Could you add one so carthage builds work properly?

**Comment by Aditi3** [comment]
Hi @codeOfRobin 

To fix the issue, In your Project, go to Carthage folder > Select **clevertap-ios-sdk** under Checkouts  > Drag the built **SDWebImage.framework** from Vendors into your Xcode Project.

Thank you for bringing this up. We will update the Carthage installation documentation for the same.

Hope this helps.

**Comment by codeOfRobin** [comment]
Oof, that'll unfortunately break things like our [Rome setup](https://github.com/blender/Rome). Is it possible to move to using a proper Cartfile instead, since that's how Carthage is supposed to work?

**Comment by codeOfRobin** [comment]
Fun fact: this also breaks for [`cocoapods-binary`](https://github.com/leavez/cocoapods-binary/) users

**Comment by Aditi3** [comment]
Hey @codeOfRobin 

Thank you for taking the time and pointing out the above concerns.

Apologies for the inconvenience caused.

We have noted all the cases, continue to investigate more and we will keep you posted on concerns. 

Unfortunately, as of now, our SDK doesn't have a Cartfile. We suggest including the dependencies in your cartfile or follow the approach I suggested in my previous comment.

Additionally, I would request to write to support@clevertap.com to help you better and take the discussion forward.

Thanks,
Aditi
