### ISSUE TITLE
Track Views in SwiftUI

### ISSUE THREAD

**Issue by moubry** [CleverTap/clevertap-ios-sdk#221]
I’m trying to use CleverTap to create a funnel for my SwiftUI app, but the way SwiftUI works with regard to [how onAppear behaves](https://blog.eidinger.info/swiftui-limitations-for-mobile-analytics), makes that very challenging.

Ideally, CleverTap would provide SwiftUI support [similar to Firebase](https://github.com/firebase/firebase-ios-sdk/tree/master/FirebaseAnalyticsSwift#after), where you just decorate your view with some metadata, and it's automatically tracked as an event when that view appears:

```swift
struct ContentView: View {
  var body: some View {
    Text("Hello, world!")
       // Logging screen name with class and a custom parameter.
      .analyticsScreen(name: "main_content",
                       class: "ContentView",
                       extraParameters: ["my_custom_param": 5])

      // OR Logging screen name only, class and extra parameters are optional.
      .analyticsScreen(name: "main_content")
  }
}
```

This is my current naive integration of CleverTap using SwiftUI:

```swift
UserProfile().onAppear {
    CleverTap.sharedInstance()?.recordEvent("User Profile Viewed")
}
```

However, ^ this doesn’t actually work in practice, because SwiftUI will execute the onAppear callback many times, at unexpected times, and out of order with how the views actually appear to the user.

It seems the correct way of doing analytics with SwiftUI apps is to swizzle UIKit’s viewDidAppear, which is a more reliable way of know what view is actually presented to the user, and then giving developers a nice API using SwiftUI to decorate their views with the appropriate metadata.

**Comment by akashvercetti** [comment]
@moubry excellent point. We will be adding this to our development/release cycle 👍

**Comment by nishant-clevertap** [comment]
@moubry 
We have added docs on steps to track screen views in swiftUI: https://developer.clevertap.com/docs/advanced-options-ios#track-screen-views-in-swiftui
Also you can refer our sample app for the implementation part: https://github.com/CleverTap/clevertap-ios-sdk/blob/master/SwiftUIStarter/SwiftUIStarter/CTViewModifier.swift

Thanks.
