### ISSUE TITLE
Batch flag read API problems

### ISSUE THREAD

**Issue by litongde** [CleverTap/clevertap-ios-sdk#222]
![image](https://user-images.githubusercontent.com/10285641/207207905-604266f9-84ba-4b95-8cdf-04d4e23597c4.png)

**Comment by akashvercetti** [comment]
@litongde noted. we will add it to the next release cycle 👍

**Comment by akashvercetti** [comment]
@laluhilmanalfa we have added a method for this in our latest release v4.2.1 https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/4.2.1 . Please update to the latest version 👍
