### ISSUE TITLE
App crashes on running [CleverTap.autoIntegrate], Conflict with OneSignal. 

### ISSUE THREAD

**Issue by j1mmyto9** [CleverTap/clevertap-ios-sdk#225]
**Describe the bug**
- My app already has `onesignal`, and now i want to integrate Clevertap also. But seem not able to use both in the project. the Project just run after I disabled one of them.

This my code to init
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        
        FirebaseApp.configure()
        CleverTap.autoIntegrate()

        OneSignal.initWithLaunchOptions(launchOptions)
        OneSignal.setAppId(oneSignalAppId)
        OneSignal.promptForPushNotifications(userResponse: { accepted in
            print("User accepted notifications: \(accepted)")
        })
}
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup OneSignal
2. Setup CleverTap
3. Run with Xcode
4. It will crash and stop Xcode in starting process

This could be a description, debug logs/console output, etc. You can also share a demo project with us where the issue is reproducible.

**Expected behaviour**
I expect to use both services in my project

**Screenshots**
<img width="1290" alt="Screenshot 2023-01-17 at 12 45 25" src="https://user-images.githubusercontent.com/9074095/212820866-3cc3adfe-52c6-439f-9b2c-4ca6a3fc2f29.png">

**Environment (please complete the following information):**
 - Xcode version: [4.2
 - CleverTap SDK Version:  CleverTap-iOS-SDK (4.2.0)
 - Device: iPhone 14 
 - OS: 16.2

**Comment by Sonal-Kachare** [comment]
Hey @j1mmyto9 

We are looking into the issue to figure out a solution to mitigate this in future release. 
Meanwhile you could manually integrate our SDK using these [steps](https://developer.clevertap.com/docs/ios#section-push-notifications).

**Comment by helderhenriquesr** [comment]
Any solutions on this case?
