### ISSUE TITLE
I want to use two different accounts for QA and production environment.

### ISSUE THREAD

**Issue by farismhmd1** [CleverTap/clevertap-ios-sdk#226]
I want to initialize clevertap based on the QA and production environment.
But currently, in the following method
`CleverTap.autoIntegrate(withCleverTapID: "")`
we can pass CleverTapID only as a  extra parameter. 
so how can I set different  CleverTapID and tokens for clevertap integration?

**Comment by akashvercetti** [comment]
@farismhmd1 starting with v3.2.0, we support multiple clevertap accounts. Here are the docs: https://developer.clevertap.com/docs/multi-instance-sdk-update#ios
