### ISSUE TITLE
Unable to add Preprocessor Macros for Location API when installing via SPM

### ISSUE THREAD

**Issue by dscyrescotti** [CleverTap/clevertap-ios-sdk#227]
### Issue
Starting from Version 3.7.0, it is mandatory to set macro value to enable Location API call. With Cocoapods, it is not problematic to add it in accordance to what documentation mentioned. However, it is not possible to add it when installing SDK via SPM because SPM doesn't support to define macro value to dependency packages. So I'm not able to trigger Location API and prompt the following warning every time I attempt.
```
[CleverTap]: To Enable CleverTap Location services/apis please build the SDK with the CLEVERTAP_LOCATION macro
```
That's why I would like to request the support to enable Location API in SPM.

### Solutions
I would like to suggest solutions that come to my mind to enable Location API in SPM. 
#### 1. Adding New Product with Location API support
In this approach, the package will include another product whose target is set with macro value so that developers can choose one of the products based on their support on Location API. It will require to symlink the original source for the target defined with macro. The manifest will be as follows.
```
let package = Package(
    products: [
        .library(
            name: "CleverTapSDK",
            targets: ["CleverTapSDK"]
        ),
        .library(
            name: "CleverTapSDK-Macro",
            targets: ["CleverTapSDK-Macro"]
        ),
    ]
    ...
    targets: [
        .target(
            name: "CleverTapSDK",
            ...
        ),
        .target(
            name: "CleverTapSDK-Macro",
            ...
            swiftSettings: [.define("CLEVERTAP_LOCATION")]
        ),
    ]
)
```
Pro: No code changes required.
Con: Complexity of defining manifest.

#### 2. Enabling Location API through Code
In this approach, the SDK will provide the functionality to enable or disable Location API in the call side so that developers can easily adjust what they actually need.

Pro: No complexity in manifest.
Con: Code changes.

The above approaches are just my ideas. There might be other proper approaches for dealing with it.

**Comment by akashvercetti** [comment]
@dscyrescotti thanks for pointing this out. We will discuss this internally and come up with a solution for this 👍

**Comment by akashvercetti** [comment]
@dscyrescotti we have added a method for this in our latest release v4.2.1 https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/4.2.1 . Please update to the latest version 👍
