### ISSUE TITLE
Push Campaign - Deeplinks opens safari

### ISSUE THREAD

**Issue by ChanBasha-MSIL** [CleverTap/clevertap-ios-sdk#229]
For campaigns when we send push notification with deeplinks(Firebase Dynamic link) it opens Safari instead of navigating to screen from app.

**Comment by ChanBasha-MSIL** [comment]
HI @nishant-clevertap ,

Yes, I have tried with custom key-value pair , it works as expected. But when we give specifically deep-link we are facing this issue. And also I tried another way like confirming **CleverTapURLDelegate** and returned **false** if channel is push notifcation  like as follows . This also solves my issue. But I am thinking whether it's right approach or not. By doing like follows will it impact another thing?

func shouldHandleCleverTap(_ url: URL?, for channel: CleverTapChannel) -> Bool {
		return channel == .pushNotification ? false : true
}

**Comment by nishant-clevertap** [comment]
Hi @ChanBasha-MSIL,

You can send different custom key-value pairs to specific platform using checkbox in same campaign as shown in below image. It is correct approach to handle universal links in iOS side. 

<img width="1418" alt="Screenshot 2023-02-02 at 4 55 54 PM" src="https://user-images.githubusercontent.com/96819882/216314528-126f20c1-e8f2-41c5-bf4c-e5ed2ae6e4ca.png">

Also you can return false only if required like if channel is push notification and if it is universal link url and you want to handle it at your end then your other push notifications  or other channels will not be affected.
