### ISSUE TITLE
Crashed: NSManagedObjectContext 0x283b744e0

### ISSUE THREAD

**Issue by laluhilmanalfa** [CleverTap/clevertap-ios-sdk#232]
Crash found in crashlytics firebase. bug starting to show in lib version 4.2.0
![Screen Shot 2023-02-22 at 10 19 37](https://user-images.githubusercontent.com/14801225/220513658-584487b5-0fba-4eeb-bc9a-12739f6b2030.png)

 - Xcode version: 13.4.1
 - CleverTap SDK Version: 4.2.0
 - Device: various Device
 - OS: Various OS Version

**Comment by Sonal-Kachare** [comment]
Could you provide us with more information or steps to reproduce the same?

**Comment by laluhilmanalfa** [comment]
i canot reproduce this bug.  its happen intermittent.
probably you can trace it by read the crashlytic log that i attach above.

**Comment by Sonal-Kachare** [comment]
Hey @laluhilmanalfa 

Thanks for the update. We'll try to figure out the steps and cause to repro this.
I'll update you soon on this.

**Comment by akashvercetti** [comment]
@laluhilmanalfa we have added a potential fix for this in our latest release v4.2.1 https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/4.2.1 . Please update to the latest version 👍

**Comment by laluhilmanalfa** [comment]
thanks a lot @akashvercetti
