### ISSUE TITLE
Crashed: SQLQueue 0x108572b30 for CleverTap-Inbox.sqlite

### ISSUE THREAD

**Issue by laluhilmanalfa** [CleverTap/clevertap-ios-sdk#233]
Bug found in crashlytics firebase.  
![Screen Shot 2023-02-22 at 10 30 35](https://user-images.githubusercontent.com/14801225/220514612-d01ba82e-1f05-4dec-83ac-a8aff939a954.png)

**Environment (please complete the following information):**
 - Xcode version: 13.4.1
 - CleverTap SDK Version: 4.2.0
 - Device: Various Device
 - OS: Various OS Version

**Comment by Sonal-Kachare** [comment]
Could you provide us with more information or steps to reproduce the same?

**Comment by laluhilmanalfa** [comment]
i canot reproduce this bug.  its happen intermittent.
probably you can trace it by read the crashlytic log that i attach above.

**Comment by Sonal-Kachare** [comment]
Hey @laluhilmanalfa 

Thanks for the update. 
Logs are showing crash in Core data. We'll try to figure out the steps and cause to repro this.
I'll update you soon on this.

**Comment by laluhilmanalfa** [comment]
thanks a lot @akashvercetti  .
