### ISSUE TITLE
Cannot hide/dismiss CTInAppHTMLViewController

### ISSUE THREAD

**Issue by FRisma** [CleverTap/clevertap-ios-sdk#236]
**Describe the bug**
When `CTInAppHTMLViewController` is displayed, if the HTML content has a button to navigate somewhere else there's no way to dismiss the ViewController.
The problem is that once a view is presented on top of the screen by CleverTap, it's almost impossible to dismiss it without some hack. CleverTap creates a new Window for displaying the ViewController (which is of type `CTInAppHTMLViewController`. So, if the view contains a button, when the user taps on it, we need to dismiss CleverTap's window. The only workaround is to iterate over the application's windows and check if the root view controller of it is of type `CTInAppHTMLViewController`. When this happens, we can hide that window.

There's a delegate that is it called when the user taps on the CTA which is
`public func shouldHandleCleverTap(_ url: URL?, for channel: CleverTapChannel) -> Bool` as part of the delegate `CleverTapURLDelegate`
Then the only way to dismiss it is by doing the following
```swift
private func attemptToRemoveCleverTapWindow() {
        let cleverTapWindow = UIApplication.shared.windows.first(where: { singleWindow in
            singleWindow.rootViewController?.description.lowercased().contains("CTInAppHTMLViewController".lowercased()) ?? false
        })
        cleverTapWindow?.isHidden = true
}
```

**To Reproduce**
1. Create CleverTap's campaign in the dashboard
2. Make sure the campaign HTML has a button (the requirement is: once the user taps on that button the clevertap modal should be dismissed) (messageType = .singleMessage) (check this real campaign id: `1677859980`)
3. Run the mobile application and see the campaign modal shown
4. Tap on the button inside the modal
5. See an error (there's no way to dismiss it)

This could be a description, debug logs/console output, etc. You can also share a demo project with us where the issue is reproducible.

**Expected behaviour**
There should be a way to dismiss or hide the UIWindow

**Screenshots**

https://user-images.githubusercontent.com/43185702/224394608-aa987f7b-404b-4a2c-b953-4a2a35537a74.mp4

**Environment (please complete the following information):**
 - Xcode version: [e.g. Xcode 11.4]
 - CleverTap SDK Version: [e.g. 4.0.0]
 - Device: [Any]
 - OS: [Any]

**Possible Solution**
Maybe ` public func shouldHandleCleverTap(_ url: URL?, for channel: CleverTapChannel) -> Bool` from `CleverTapURLDelegate ` should have an extra parameter (like the UIWindow reference) to be able to hide it. Just a suggestion

**Additional context**

**Comment by AishwaryaNanna** [comment]
Hi @FRisma ,
We are debugging this and will let you know the progress.
Thanks!

**Comment by akashvercetti** [comment]
@FRisma Could you please help us understand your use case here? We provide a cross(X) button at the top right of the inapp view controller to dismiss it.
From what I can see from the video, you are maybe pushing some view controller(s) to the stack on click of the HTML button from the in-app view controller, followed by pressing the cross button at the top-right to dismiss the in-app. 
Could you explain your use-case flow in detail? Along with an example HTML if possible.
@darshanclevertap @AishwaryaNanna

**Comment by FRisma** [comment]
@akashvercetti sorry for the delay, the HTML does triggers an app deeplink when the user taps on the button shown. When that happens, we want to trigger the deeplink to navigate to a different part of the app, but also dismiss the modal (not by pressing the X button at the top right, but automatically).
<img width="259" alt="image" src="https://user-images.githubusercontent.com/43185702/229598840-fa9ccaa4-ba20-4595-a5f3-7b0c01fda572.png">

What I want: Be allowed to dismiss whatever view (or viewController) CleverTapSDK had shown on the app when this method is called.
```swift
public func shouldHandleCleverTap(_ url: URL?, for channel: CleverTapChannel) -> Bool
```
As you can see, that method does not have a reference to the view, viewController or the window that's being triggering that call: `shouldHandleCleverTap(url:for)` therefore, I cannot place some business logic to dismiss the view on that delegate adoption

**Comment by akashvercetti** [comment]
@FRisma could you please add `window.location.href = "wzrk://exit` to your button onclick and try it out?

**Comment by LogiCCPL** [comment]
I have exactly the same problem. When I press the action button with deeplink on the In-App Notification, it stays on the screen all the time and the action from the deeplink is triggered.
