### ISSUE TITLE
-[CTInboxController deleteMessagesWithId:] + 108

### ISSUE THREAD

**Issue by litongde** [CleverTap/clevertap-ios-sdk#241]
Fatal Exception: NSInvalidArgumentException
*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x9e38 __exceptionPreprocess
1  libobjc.A.dylib                0x178d8 objc_exception_throw
2  CoreFoundation                 0x1af078 -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x1abaa0 -[__NSArrayM insertObject:atIndex:].cold.2
4  CoreFoundation                 0x13f40 -[__NSArrayM insertObject:atIndex:]
5  CleverTapSDK                   0x453a8 -[CTInboxController deleteMessagesWithId:] + 108 (CTInboxController.m:108)
6  CleverTapSDK                   0x1bfc0 -[CleverTap deleteInboxMessagesForIDs:] + 4347 (CleverTap.m:4347)
7  eWallet-iOS                    0x16d983c __59+[TNGCleverTapHandle deleteInboxMessageWithIds:completion:]_block_invoke
8  libdispatch.dylib              0x2460 _dispatch_call_block_and_release
9  libdispatch.dylib              0x3f88 _dispatch_client_callout
10 libdispatch.dylib              0xb720 _dispatch_lane_serial_drain
11 libdispatch.dylib              0xc18c _dispatch_lane_invoke
12 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread
13 libsystem_pthread.dylib        0xdf8 _pthread_wqthread
14 libsystem_pthread.dylib        0xb98 start_wqthread

![image](https://user-images.githubusercontent.com/10285641/228440980-78306767-c31a-4232-af03-a13ae1548cb3.png)

**Comment by litongde** [comment]
The error is obvious. Please help fix it. object cannot be nil

**Comment by nishant-clevertap** [comment]
Hi @litongde,

In which CleverTap iOS SDK version you are facing this exception? This was known issue and has been fixed in our latest version v4.2.1. Refer changelog: https://github.com/CleverTap/clevertap-ios-sdk/blob/master/CHANGELOG.md#version-421-march-22-2023

Do update to our latest version v4.2.1 and let us know if this is fixed or not. 

Thanks.

**Comment by litongde** [comment]
> 

The SDK version I am currently using is v4.2.0. I will update my SDK version to v4.2.1 and try again. Thank you very much for your answer.
