### ISSUE TITLE
Retrieving unread messages from the Inbox causes the thread to get stuck

### ISSUE THREAD

**Issue by litongde** [CleverTap/clevertap-ios-sdk#248]
![image](https://user-images.githubusercontent.com/10285641/233582006-e9dbc2df-bbc5-4ac8-813f-ab36148491fc.png)

Retrieving unread messages from the Inbox may cause a thread to get stuck. This problem appears in 4.2.2. No problem with 4.2.0

**Comment by litongde** [comment]
Hi @nishant-clevertap 

The problem is probabilistic, and the probability is high.
The deleteInboxMessageForID method had a similar problem before. We added a new child thread queue to do this. Now getInboxMessageUnreadCount method in v4.2.2 version also appears stuck thread. Simply encapsulating the subthread queue will not solve the fundamental problem. It is recommended that you try to operate the recurrence in multithreaded concurrent situations. The main issue is thread safety in the inbox coredata manipulation area.

**Comment by litongde** [comment]
![image](https://user-images.githubusercontent.com/10285641/234200900-3e23d65f-340d-4c34-95ae-3ffac7c20982.png)

![image](https://user-images.githubusercontent.com/10285641/234201066-9c1e5efc-1b3e-4cab-b5cd-2b1422b834ea.png)

**Comment by nishant-clevertap** [comment]
Hi @litongde,
Thanks for the detailed information. We will investigate this and will get back to you.

**Comment by nishant-clevertap** [comment]
Hi @litongde,
Can you share the full stack trace report to check if other threads are sharing any common resource or not?

**Comment by litongde** [comment]
Version 5.0.1 still has this problem, as shown in the following figure stack information.
It is easier to repeat the problem when switching user accounts to login.

![ct_1](https://github.com/CleverTap/clevertap-ios-sdk/assets/10285641/8577c5a6-5e92-474e-a658-6476f2d30036)

![ct_2](https://github.com/CleverTap/clevertap-ios-sdk/assets/10285641/2347ea4c-0275-40b6-991a-4cb3f2a922ba)

**Comment by litongde** [comment]
![image](https://github.com/CleverTap/clevertap-ios-sdk/assets/10285641/18b07bbb-8d2f-4859-b8ce-b0d4071b8411)

![image](https://github.com/CleverTap/clevertap-ios-sdk/assets/10285641/a0741c89-1aff-4a01-9e1e-4e47f6deac1c)

**Comment by akashvercetti** [comment]
@litongde We are still trying to debug and reproduce this issue by replicating your `TNGCleverTapHandle` class. In the meantime, could you please help us speed this up?

Could you please create a sample iOS app project with just the `TNGCleverTapHandle` class along with the CleverTap App Inbox initialisation/implementation code. I can see from the latest stack trace that you have called `TNGCleverTapHandle` inbox method from your ViewController's `viewDidLoad` method. Could you replicate this in a sample app and share it with us. Please remove any sensitive data/code from your class.

**Comment by litongde** [comment]
> @litongde We are still trying to debug and reproduce this issue by replicating your `TNGCleverTapHandle` class. In the meantime, could you please help us speed this up?
> 
> * Could you please create a sample iOS app project with just the `TNGCleverTapHandle` class along with the CleverTap App Inbox initialisation/implementation code. I can see from the latest stack trace that you have called `TNGCleverTapHandle` inbox method from your ViewController's `viewDidLoad` method. Could you replicate this in a sample app and share it with us. Please remove any sensitive data/code from your class.
> * Could you share your code when you switch accounts/login?

Can you retry using iPhone6 OS version 12.5.5? It's basically a must on this phone.

**Comment by akashvercetti** [comment]
we have released a potential fix for this in our latest release v5.1.0. Could you please try updating to it?
https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/5.1.0
