### ISSUE TITLE
App Store Location Warning with SwiftPM Integration

### ISSUE THREAD

**Issue by FabrizioBrancati** [CleverTap/clevertap-ios-sdk#255]
**Describe the bug**
We recently updated from 4.1.1 to 4.2.2 and we got a warning email from Apple because we started using Location APIs without setting a `NSLocationWhenInUseUsageDescription` string description in the Info.plist file.
Our app doesn't use any Location APIs, and from version 4.2.1 of the SDK [a new API has been added to allow Location API usage with SwiftPM](https://github.com/CleverTap/clevertap-ios-sdk/blob/master/CHANGELOG.md#added-1). The new API is [`enableLocation` which is not under the `CLEVERTAP_LOCATION` compilation flag](https://github.com/CleverTap/clevertap-ios-sdk/blob/9be7d5c34fdff561948f44408a10e97918f91c24/CleverTapSDK/CleverTap.m#L4004C1-L4023) that [was not working for SwiftPM](https://github.com/CleverTap/clevertap-ios-sdk/issues/227).
So, from 4.2.1 the Location code will be compiled even if not used, which [was not the case for 4.2.0](https://github.com/CleverTap/clevertap-ios-sdk/blob/4.2.0/CleverTapSDK/CleverTap.m#L4081-L4087) and below.

This prevents us from updating the SDK to a newer version and updating to Xcode 14.3 which [was fixed by the 4.2.2 SDK version](https://github.com/CleverTap/clevertap-ios-sdk/blob/master/CHANGELOG.md#fixed-1).

The same issue is still present in the 5.0.0 SDK version.

**Expected behaviour**
The Location code should not be compiled at all if the CleverTap SDK is added via SwiftPM and the `CLEVERTAP_LOCATION` is not added to the project.

**Environment:**
 - Xcode version: 14.3
 - CleverTap SDK Version: From 4.2.2 to 5.0.0

**Comment by akashvercetti** [comment]
Thanks for bringing this up. The problem was SPM projects did not work with macros like Cocoapods projects did. We will discuss this internally and come up with a solution for this issue, that suits both SPM and other projects 👍.

**Comment by akashvercetti** [comment]
We have released a fix for this in our latest release v5.0.1
https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/5.0.1

**Comment by FabrizioBrancati** [comment]
@akashvercetti Thank you! We will try it and let you know 🙌
