### ISSUE TITLE
Non-void function does not return a value in all control paths

### ISSUE THREAD

**Issue by yuvrajchaudhari03** [CleverTap/clevertap-ios-sdk#259]
**Describe the bug**
Getting this error **Non-void function does not return a value in all control paths**

**Screenshots**
<img width="1392" alt="Screenshot 2023-05-24 at 10 28 54 PM" src="https://github.com/CleverTap/clevertap-ios-sdk/assets/52877982/dc4c07c5-63e5-49fd-bae2-0470cef529c3">

**Environment (please complete the following information):**
 - Xcode version: 14.3
 - clevertap-react-native Version: 0.9.3
 - iPhone 
 - OS: iOS 13.4

**Comment by akashvercetti** [comment]
@yuvrajchaudhari03 Please update to the latest React native SDK v1.0.3 to fix Xcode 14.3 related errors.

**Comment by yuvrajchaudhari03** [comment]
@akashvercetti after updating React native SDK to v1.0.3 getting these errors in xcode
<img width="264" alt="Screenshot 2023-05-25 at 1 11 43 PM" src="https://github.com/CleverTap/clevertap-ios-sdk/assets/52877982/df5b893e-7960-4a2b-8722-e0229c7eb00c">

**Comment by akashvercetti** [comment]
@yuvrajchaudhari03 please share your integration code or provide detailed errors

**Comment by ralphcorleone** [comment]
@akashvercetti It happened to me in the native version of the SDK.

Environment:
Xcode version: 14.3
M1
CleverTap-iOS-SDK Version: 4.1.4 (tested too in 3.10.0)
Simulador
OS: iOS 16.4

**Comment by Anubhavjain786** [comment]
![Screenshot 2023-06-19 at 10 32 58 PM](https://github.com/CleverTap/clevertap-ios-sdk/assets/34815687/a4a60362-77ed-4f95-b7e9-2f9d0b9ab06d)

I'm getting this same issue.

**Comment by akashvercetti** [comment]
@Anubhavjain786 Please update to the latest iOS SDK v5.0.1 to resolve this issue.
