### ISSUE TITLE
Getting Error User/.../Pods/CleverTap-iOS-SDK/CleverTapSDK/CTLocalDataStore.m:416:1 Non-void function does not return a value in all control paths

### ISSUE THREAD

**Issue by muhammednadeem-workspace** [CleverTap/clevertap-ios-sdk#261]
getting this error after updating to Xcode 14.3.1 
<img width="224" alt="Screenshot 2023-06-12 at 10 55 45 PM" src="https://github.com/CleverTap/clevertap-ios-sdk/assets/111335366/7a56849c-cf4b-4558-b791-8950d8365589">

**Comment by akashvercetti** [comment]
@muhammednadeem-workspace Please update to the latest version v5.0.1 to resolve these issues 
https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/5.0.1

**Comment by muhammednadeem-workspace** [comment]
Hi @akashvercetti we have a minimum iOS support of 11, will i be able to update to this pod version

**Comment by akashvercetti** [comment]
@muhammednadeem-workspace I believe the SDK supports a minimum of iOS 9, so you should be good 👍

**Comment by adamkoot** [comment]
> @muhammednadeem-workspace Please update to the latest version v5.0.1 to resolve these issues https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/5.0.1

For me it doesn't work. I tried to downgrade xcode, clevertap package, but still same error;

Problem on xcode 14.3.1; 
clevertap-ios-skd 5.0.1
macbook air on intel 

any ideas ?

**Comment by akashvercetti** [comment]
@adamkoot could you please provide us with the error thrown by Xcode, via text or screenshot? 
Also, could you please double check your pods if v5.0.1 is installed? Maybe trying `pod install --repo-update` after deleting `Podfile.lock`

**Comment by adamkoot** [comment]
@akashvercetti I did what you said, still same issue 


![Screenshot 2023-06-21 at 11 33 44](https://github.com/CleverTap/clevertap-ios-sdk/assets/65679285/10b12850-1267-4ec8-b36c-b32b63b185ae)

<img width="993" alt="Screenshot 2023-06-21 at 11 39 30" src="https://github.com/CleverTap/clevertap-ios-sdk/assets/65679285/21dc8cb8-30f3-4a6c-b2d4-67fe89fa4fc8">

**Comment by akashvercetti** [comment]
@adamkoot The screenshot is of an older version code of the ios sdk. If you are using CleverTap react native sdk, please update to the latest version v.1.1.1 and then install pods/rebuild your ios project. 
https://github.com/CleverTap/clevertap-react-native/releases/tag/1.1.1

**Comment by adamkoot** [comment]
@akashvercetti working and building, thanks for help!
