### ISSUE TITLE
Retrieving unread messages from the Inbox causes the thread to get stuck

### ISSUE THREAD

**Issue by litongde** [CleverTap/clevertap-ios-sdk#264]
https://github.com/CleverTap/clevertap-ios-sdk/issues/248

Version 5.0.1 still has this problem, as shown in the following figure stack information.
It is easier to repeat the problem when switching user accounts to login.

![ct_1](https://github.com/CleverTap/clevertap-ios-sdk/assets/10285641/3050f7f0-fe7f-4a07-a499-99f9c52ec9db)

![ct_2](https://github.com/CleverTap/clevertap-ios-sdk/assets/10285641/b0627068-fe10-4dbc-8de0-746f60625b32)

**Comment by litongde** [comment]
@nishant-clevertap 

This problem is not a problem on version 4.2.0, hope to help urgent check. Because of this problem, we can not easily upgrade xcode to 14.3, only the new version of the clevertap sdk to fix the 14.3 compilation error, but the new version will cause thread stuck. In a hurry

**Comment by akashvercetti** [comment]
we have released a potential fix for this in our latest release v5.1.0. Could you please try updating to it?
https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/5.1.0
