### ISSUE TITLE
Depond on SDWebImage/GIF 4.0. How can I update SDWebImage to Version 5.0

### ISSUE THREAD

**Issue by csjlengxiang** [CleverTap/clevertap-ios-sdk#27]
This sdk depond on SDWebImage/GIF 4.0.
 How can I update SDWebImage to Version 5.0

**Comment by mavericksunny** [comment]
+1

**Comment by sivakumar-cf** [comment]
+1

**Comment by Aditi3** [comment]
Hi @csjlengxiang, @mavericksunny, and @sivakumar-cf 

We have already started working on updating the SDWebImage to version 5.x.

The release with SDWebImage 5.x will be available soon. We will keep you posted.

Thanks,
Aditi

**Comment by Aditi3** [comment]
Hi @csjlengxiang , @mavericksunny , and @sivakumar-cf 

I am glad to inform that we have released support for SDWebImage version 5.0.

Here is the link of the latest release that comes with the SDWebImage 5.0 support

https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/3.6.0

Thanks for your patience.

Aditi

**Comment by sivakumar-cf** [comment]
@Aditi3  Can you please update this in https://github.com/CleverTap/clevertap-react-native as well?

**Comment by Aditi3** [comment]
Hey @sivakumar-cf 

Could you try updating your React Native project podfile with CleverTap iOS SDK to version 3.6.0? 

Hope this helps.

If you need more help for your React Native Project do open an issue for https://github.com/CleverTap/clevertap-react-native repo or write to support@clevertap.com.

Thanks,
Aditi
