### ISSUE TITLE
Cocoapods 'Generated duplicate UUIDs' warning when integrating 5.0.1

### ISSUE THREAD

**Issue by kuldar-daniel** [CleverTap/clevertap-ios-sdk#271]
When integrating SDK version 5.0.1 via CocoaPods, we receive following rather concerning warning:

**CocoaPods output**

```
[!] [Xcodeproj] Generated duplicate UUIDs:

PBXFileReference -- Pods.xcodeproj/mainGroup/children/children:children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,
....
<group>,,isa:PBXBuildFile,settings:ATTRIBUTES:Public,,
```

**Podfile:**

```
use_frameworks!

platform :ios, '14.0'

target 'CleverTap Integration' do
  pod "CleverTap-iOS-SDK", '~> 5.0.1'
end
```

**To reproduce:** https://github.com/kuldar-daniel/clevertap-cocoapods-issue

1. Run `pod install` in the Sample project repo

**Environment**
 - Xcode version: 14.2
 - CleverTap SDK Version: 5.0.1
 - OS: 13.3.1
 - CocoaPods: v.1.11.3

**Comment by alediazlucky** [comment]
I can confirm that this is also happening in the following environment:

- Xcode version: 14.3.1
- CleverTap SDK Version: 5.0.0
- macOS: 13.4
- CocoaPods: v.1.12.1

**Comment by akashvercetti** [comment]
We are currently investigating this and will let you know when we make progress. In the meantime, a potential fix has been suggested at the Cocoapods repo: https://github.com/CocoaPods/CocoaPods/issues/4370#issuecomment-183205691

**Comment by enikeevrinat** [comment]
@akashvercetti please kindly review the [proposed fix](https://github.com/CleverTap/clevertap-ios-sdk/pull/275), our team needs the solution asap

**Comment by akashvercetti** [comment]
We have released a fix for this proposed by @enikeevrinat in our latest release v5.1.1: https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/5.1.1
