### ISSUE TITLE
Clevertap SDK 4.1.0 fails to compile on Xcode 14.3

### ISSUE THREAD

**Issue by suryasahu92** [CleverTap/clevertap-ios-sdk#277]
We are having issues while adapting to Xcode 14.3 on Clevertap SDK 4.1.0 on the class CTLocalDataStore.

Can you guys confirm if the same is resolved in incremental version or the latest version. If YES please do share the details on same

@ygit @Aditi3  @Darshanpania

**Comment by akashvercetti** [comment]
@suryasahu92 all releases from v4.2.2 support Xcode 14.3. 
https://github.com/CleverTap/clevertap-ios-sdk/blob/master/CHANGELOG.md#version-422-april-03-2023

**Comment by suryasahu92** [comment]
Thanks @akashvercetti  for the update
