### ISSUE TITLE
 'Non-void function does not return a value in all control paths' error in CleverTap with Xcode 14.3.1

### ISSUE THREAD

**Issue by Anoopkmr1** [CleverTap/clevertap-ios-sdk#281]
In Xcode 14.3.1, we are using the CleverTap ios sdk -3.9.2 and also tried with the 5.1.2,but the framework encounters an error message stating **"Non-void function does not return a value in all control paths."** This error indicates that a function in the sdk codebase is expected to return a value, but there are certain control paths where no value is being returned. Please let us know that whether the clevertap is able to integrated in xcode 14.3.1 or not. 
Xcode- 14.3.1
iOS - 13.0
 Your response will be highly appreciated.

**Comment by nishant-clevertap** [comment]
Hi @Anoopkmr1 
Can you share the screenshot of the file where you are getting this error?

**Comment by Anoopkmr1** [comment]
Please find the Screen shot the error 
<img width="1724" alt="Screenshot 2023-08-01 at 4 26 31 PM" src="https://github.com/CleverTap/clevertap-ios-sdk/assets/108727695/5894c556-7e21-42ff-99da-2fd9ed1aa498">
