### ISSUE TITLE
App crash - CTAlertViewController showFromWindow

### ISSUE THREAD

**Issue by Praphin** [CleverTap/clevertap-ios-sdk#292]
**Describe the bug**
App is getting crashed with following error
Fatal Exception: NSInternalInconsistencyException
UIViewController is missing its initial trait collection populated during initialization. This is a serious bug, likely caused by accessing properties or methods on the view controller before calling a UIViewController initializer. View controller: <CTAlertViewController: 0x10f813ff0>

**Screenshots**
<img width="956" alt="Screenshot 2023-09-25 at 10 19 58 PM" src="https://github.com/CleverTap/clevertap-ios-sdk/assets/6714897/1ceeac3d-4dd2-4c4f-b07c-eb0d432a6abc">
<img width="1224" alt="Screenshot 2023-09-25 at 10 20 14 PM" src="https://github.com/CleverTap/clevertap-ios-sdk/assets/6714897/74d2df1a-3233-4b0b-8586-d42c1d5fc399">

**Environment (please complete the following information):**
 - Xcode version: Xcode 15
 - CleverTap SDK Version: 4.2.2
 - Device: iPhone12, iPhone SE 
 - OS:  iOS 17

**Comment by Praphin** [comment]
@akashvercetti I can update version and check on the next release. Meanwhile any plans for above PR on Master release ?

**Comment by akashvercetti** [comment]
@Praphin we are planning to release a new version this week.

**Comment by vkochukov** [comment]
I sorry to write a comment in this issue, but it seems to me that this is the same problem. [clevertap-react-native](https://github.com/CleverTap/clevertap-react-native) has a similar issue. It works fine with your [changes](https://github.com/CleverTap/clevertap-ios-sdk/pull/293)

Could you please fix it there too?

Environment:
Xcode version: Xcode 15
CleverTap React Native SDK Version: 1.2.0
Device: iPhone 15
OS: iOS 17

**Comment by akashvercetti** [comment]
@vkochukov we will release a fix for react native too. We will keep you updated on the release 👍

**Comment by kartikthakur2022** [comment]
Please release fix for  https://github.com/CleverTap/clevertap-cordova also.
Thanks

**Comment by akashvercetti** [comment]
We have released a fix for this in our latest release for:
- ios: https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/5.2.1
- react native: https://github.com/CleverTap/clevertap-react-native/releases/tag/1.2.1
- cordova: https://github.com/CleverTap/clevertap-cordova/releases/tag/2.7.2
