### ISSUE TITLE
iOS 17 New required reason API

### ISSUE THREAD

**Issue by lakshmankreditbee** [CleverTap/clevertap-ios-sdk#295]
From Apple's newly published document ["Describing use of required reason API"](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api):

> Your app or third-party SDK must declare one or more approved reasons that accurately reflect your use of each of these APIs and the data derived from their use. You may use these APIs and the data derived from their use for the declared reasons only. These declared reasons must be consistent with your app’s functionality as presented to users, and you may not use the APIs or derived data for tracking.

Will clevertap-ios-sdk be either removing the use of these APIs or providing a privacy manifest file for the iOS SDK? Or perhaps are you in contact with Apple about this issue?

**Comment by nishant-clevertap** [comment]
Hi @lakshmankreditbee 
We are looking into this and we will get back to you soon.

**Comment by lakshmankreditbee** [comment]
Hi, when can we expect an update regarding this issue?

**Comment by akashvercetti** [comment]
@lakshmankreditbee This will be released sometime in February the latest.

**Comment by akashvercetti** [comment]
We have added this in our latest release 6.1.0 👍 
https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/6.1.0
