### ISSUE TITLE
Xcode warnings for the clevertap-ios-sdk package

### ISSUE THREAD

**Issue by ingopaulsen** [CleverTap/clevertap-ios-sdk#299]
**Describe the bug**
I have received the following warnings in Xcode for the clevertap-ios-sdk package (the numbers in brackets indicate the frequency):

- (1) 'archiveRootObject:toFile:' is deprecated: first deprecated in iOS 12.0 - Use +archivedDataWithRootObject:requiringSecureCoding:error: and -writeToURL:options:error: instead
- (1) 'automaticallyAdjustsScrollViewInsets' is deprecated: first deprecated in iOS 11.0 - Use UIScrollView's contentInsetAdjustmentBehavior instead
- (4) 'CleverTapFeatureFlagsDelegate' is deprecated: This protocol has been deprecated and will be removed in the future versions of this SDK.
- (5) 'CleverTapProductConfigDelegate' is deprecated: This protocol has been deprecated and will be removed in the future versions of this SDK.
- (1) 'ctFeatureFlagsUpdated' is deprecated: This protocol method has been deprecated and will be removed in the future versions of this SDK.
- (1) 'ctProductConfigActivated' is deprecated: This protocol method has been deprecated and will be removed in the future versions of this SDK.
- (1) 'ctProductConfigFetched' is deprecated: This protocol method has been deprecated and will be removed in the future versions of this SDK.
- (1) 'ctProductConfigInitialized' is deprecated: This protocol method has been deprecated and will be removed in the future versions of this SDK.
- (1) 'currentRadioAccessTechnology' is deprecated: first deprecated in iOS 12.0
- (1) 'subscriberCellularProvider' is deprecated: first deprecated in iOS 12.0
- (3) 'topLayoutGuide' is deprecated: first deprecated in iOS 11.0 - Use view.safeAreaLayoutGuide.topAnchor instead of topLayoutGuide.bottomAnchor
- (2) 'unarchiveObjectWithFile:' is deprecated: first deprecated in iOS 12.0 - Use +unarchivedObjectOfClass:fromData:error: instead
- (2) 'UILocalNotification' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationRequest

**Screenshot**

<img width="1355" alt="CleverTapSDK_iOS" src="https://github.com/CleverTap/clevertap-ios-sdk/assets/203617/cb360162-9f88-40b5-8f4c-106406f40a35">

**Environment:**
 - Xcode version: Xcode 15.0
 - CleverTap SDK Version: v5.2.1
 - Device: iPhone7
 - Simulator: iPhone15
 - OS: iOS 15+

**Comment by akashvercetti** [comment]
@ingopaulsen We are working on removing these warnings and will be including them in the next release.
https://github.com/CleverTap/clevertap-ios-sdk/tree/task/SDK-3419-remove-warnings

**Comment by ingopaulsen** [comment]
Thank you, Akash

**Comment by akashvercetti** [comment]
@ingopaulsen we have released a fix for this in our latest release v5.2.2 👍 
https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/5.2.2
