### ISSUE TITLE
Opt-out for Push Notifications on Specific Device in CleverTap User Profile

### ISSUE THREAD

**Issue by RobertAdamczyk** [CleverTap/clevertap-ios-sdk#305]
I am currently dealing with a minor issue. I noticed that in the user profile, there's a list of devices associated with the user. If a user has granted permission for push notifications, a green notification icon is displayed next to the respective device (see attached screenshot).

Is there a way to implement an opt-out specifically for push notifications on an individual device?

<img width="1420" alt="Screenshot 2023-12-06 at 10 37 47" src="https://github.com/CleverTap/clevertap-ios-sdk/assets/137081573/0bff29ba-eba8-4cb5-a2a3-94ccc35b32c3">

**Comment by nishant-clevertap** [comment]
Hi @RobertAdamczyk,
Yes, you can opt-out for push notification for specific device. You have to set "MSG-push" property to NO for that specific device. You can refer this doc: https://developer.clevertap.com/docs/user-profiles-ios#updating-user-profilepush-profile-method to update the user property, for this you can use: `@"MSG-push": @NO`.

**Comment by RobertAdamczyk** [comment]
Yes, it works as expected. Thank you for the prompt support.
