### ISSUE TITLE
Undefined symbols SDAnimatedImage SDImageCache and SDWebImageContextStoreCacheType

### ISSUE THREAD

**Issue by jrobichaud** [CleverTap/clevertap-ios-sdk#315]
**Describe the bug**
I am unable to link. Clevetap iOS SDK 5.0.1

```
ld: Undefined symbols:
  _OBJC_CLASS_$_SDAnimatedImage, referenced from:
       in CTInAppNotification.o
  _OBJC_CLASS_$_SDImageCache, referenced from:
       in CTVideoThumbnailGenerator.o
  _SDWebImageContextStoreCacheType, referenced from:
      -[CTInboxBaseMessageCell _sharedInit] in CTInboxBaseMessageCell.o
      -[CTCarouselImageView loadImage] in CTCarouselImageView.o
```

We also have this warning:
```
Link CleverTapSDK (arm64)229"Ld /Users/jules/Library/Developer/Xcode/DerivedData/<PROJECT NAME>/Debug-iphoneos/CleverTap-iOS-SDK/CleverTapSDK.framework/CleverTapSDK normal (in target 'CleverTap-iOS-SDK' from project 'Pods')5b0a325037bdc541^bfef415037bdc541^-571"ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
```

**To Reproduce**

We use:

```
@leanplum/react-native-sdk: 2.1.0
leanplum iOS SDK: 6.1.0
clevertap-react-native: 1.1.1
clevertap iOS SDK: 5.0.1
```

Along with SDWebImage 5.11.1 (We cannot use a more recent version of SDWebImage because we use RNFastImage which freezes it to `~>5.11.1`.)

**Expected behaviour**
Link with no error.

**Screenshots**
-

**Environment (please complete the following information):**
 - Xcode version: 15.2
 - CleverTap SDK Version: 5.0.1
 - Device: iPhone12 Pro
 - OS: iOS 17.3.1

**Possible Solution**
-

**Additional context**
- we are only supposed to update Leanplum iOS SDK but this SDK is a required dependency.

**Comment by nzagorchev** [comment]
Leanplum SDK needs to be linked dynamically in the context of React Native. This means that its dependencies also need to be linked dynamically.

`
dynamic_frameworks = ['Leanplum-iOS-SDK', 'CleverTap-iOS-SDK', 'SDWebImage']
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
        if dynamic_frameworks.include?(pod.name)
          puts "Setting dynamic linking for #{pod.name}"
          def pod.build_type;
            Pod::BuildType.dynamic_framework
          end
        end
      end
  end
`

**Comment by jrobichaud** [comment]
Thanks @nzagorchev , I believe it is the only thing I did not try. 😅
