### ISSUE TITLE
Crash when footer campaign appears (or is dismissed).

### ISSUE THREAD

**Issue by leandromperez** [CleverTap/clevertap-ios-sdk#33]
Whenever a footer campaign is triggered, the app crashes just a second after the footer appears. 

I imagine it crashes when the footer disappears.

The crash logs are not yielding any relevant information, but the crash has been consistently this one:

```
Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSConcretePointerArray pointerAtIndex:]: attempt to access pointer at index 2 beyond bounds 2'
*** First throw call stack:
(0x1b3bec98c 0x1b39150a4 0x1b3eb59e0 0x1b7e23fa8 0x1b7e238ec 0x1b7c44814 0x1b7c44ba4 0x1b7c84c54 0x1b7c94590 0x1b7c884a4 0x1b7c8b998 0x1b7c8480c 0x1b3b6a7e0 0x1b3b6a738 0x1b3b69ed0 0x1b3b6501c 0x1b3b648bc 0x1bd9c9328 0x1b7bf9a70 0x1039670a4 0x1b39ef460)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	0x19433c98c __exceptionPreprocess + 220 (NSException.m:199)
1   libobjc.A.dylib               	0x1940650a4 objc_exception_throw + 56 (objc-exception.mm:565)
2   Foundation                    	0x1946059e0 -[NSConcretePointerArray pointerAtIndex:] + 248 (NSPointerArray.m:442)
3   UIKitCore                     	0x198573db8 -[UIWindowScene _enumerateWindowsIncludingInternalWindows:onlyVisibleWindows:asCopy:stopped:withB... + 224 (UIWindowScene.m:679)
4   UIKitCore                     	0x1985736fc -[UIWindowScene _topVisibleWindowPassingTest:] + 444 (UIWindowScene.m:592)
5   UIKitCore                     	0x198394478 +[UIWindow _hitTestToPoint:forEvent:windowServerHitTestWindow:] + 236 (UIWindow.m:6395)
6   UIKitCore                     	0x198394808 -[UIWindow _targetWindowForPathIndex:atPoint:forEvent:windowServerHitTestWindow:] + 180 (UIWindow.m:6441)
7   UIKitCore                     	0x1983d4a54 ____updateTouchesWithDigitizerEventAndDetermineIfShouldSend_block_invoke.52 + 768 (UIEventDispatcher.m:132)
8   UIKitCore                     	0x1983e4390 _UIEventHIDEnumerateChildren + 144 (UIEventHIDHelpers.m:35)
9   UIKitCore                     	0x1983d82a4 __dispatchPreprocessedEventFromEventQueue + 1888 (UIEventDispatcher.m:1020)
10  UIKitCore                     	0x1983db798 __handleEventQueueInternal + 4924 (UIEventDispatcher.m:2007)
11  UIKitCore                     	0x1983d460c __handleHIDEventFetcherDrain + 108 (UIEventDispatcher.m:1975)
12  CoreFoundation                	0x1942ba7e0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24 (CFRunLoop.c:1922)
13  CoreFoundation                	0x1942ba738 __CFRunLoopDoSource0 + 80 (CFRunLoop.c:1956)
14  CoreFoundation                	0x1942b9ed0 __CFRunLoopDoSources0 + 180 (CFRunLoop.c:1992)
15  CoreFoundation                	0x1942b501c __CFRunLoopRun + 1080 (CFRunLoop.c:2882)
16  CoreFoundation                	0x1942b48bc CFRunLoopRunSpecific + 464 (CFRunLoop.c:3192)
17  GraphicsServices              	0x19e119328 GSEventRunModal + 104 (GSEvent.c:2246)
18  UIKitCore                     	0x1983496d4 UIApplicationMain + 1936 (UIApplication.m:4753)
19  OurApp                          	0x1049a8cbc main + 300 (main.swift:18)
20  libdyld.dylib                 	0x19413f460 start + 4
```

Removing the campaign just fixes the problem.

**Comment by kabram** [comment]
I am seeing the same issue crash with top banner in app message on iOS 13 only. The crash occurs if you put app to background on iOS 13 while the top banner is present.

**Comment by Aditi3** [comment]
Hey @leandromperez @kabram 

We too have noticed such crashes with Header/ Footer Mobile in-apps on iOS 13.0 and same appears to be working rightly on iOS 12.x and below. Seems like Apple did some change related to UIWindow APIs.

Nonetheless, To handle such crashes in iOS 13.0 we have added a fix in our latest release i.e [3.7.0](https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/3.7.0)

I request you to upgrade CleverTap SDK to 3.7.0 and verify the same.
 
After the update, it should be working correctly.

Sorry for the inconvenience caused.

**Comment by leandromperez** [comment]
Hi @Aditi3 
Thanks for your response. We use Segment-Clevertap. Any idea when that will be available?

**Comment by Aditi3** [comment]
Hi @leandromperez 

The Segment-CleverTap SDK release is planned for early next week.

**Comment by Aditi3** [comment]
Hey @leandromperez 

I am happy to inform that we have released Segment-CleverTap SDK pointing to the latest version [3.7.0](https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/3.7.0)

Here is the link of the latest release that comes with the Header/ Footer Mobile in-apps crash fix on iOS 13.x.
https://github.com/CleverTap/clevertap-segment-ios/releases/tag/1.1.1

Thanks for your patience.

Aditi

**Comment by leandromperez** [comment]
Hi,
I cannot test this because the Clevertap dashboard is not allowing me to
create a test campaign. I cannot re-open archived ones either. It says the
plan reached its limit.
Can you do something about it?

Thanks,
Leandro

**Comment by Aditi3** [comment]
Hi @leandromperez 

Would request you to write to support@clevertap.com regarding this query. Definitely somebody from our support will assist you with this.

**Comment by FoneG** [comment]
Can you please share what caused this? I didn't use clevertap sdk, but I still had this kind of crash, if you can give me any thoughts, I would be very grateful!  @Aditi3
