### ISSUE TITLE
Fatal Exception: NSInternalInconsistencyException

### ISSUE THREAD

**Issue by TimotiusLeonardo** [CleverTap/clevertap-ios-sdk#334]
**Describe the bug**
this bug created 2 seconds after user open the app / after launchscreen is dismissed. I don't really know how to reproduce it, because it happened in production app, and i can't produce it. But it affecting some of my user and sometimes the got force close.
I assume it is because banner in app from clevertap that can show as an overlay in our app to show some ads or etc.

**Evidence**
This evidence i got from Firebase Dashboard, and this is the output:
`
Fatal Exception: NSInternalInconsistencyException
UIViewController is missing its initial trait collection populated during initialization. This is a serious bug, likely caused by accessing properties or methods on the view controller before calling a UIViewController initializer. View controller: <CTAlertViewController: 0x102c44410>
`

**Expected behaviour**
-

**Screenshots**
![image](https://github.com/CleverTap/clevertap-ios-sdk/assets/60493932/739b986b-1772-4c1d-a93c-53572f050c28)

**Environment (please complete the following information):**
 - Xcode version: 15.4 (CI/CD = 15.1)
 - CleverTap SDK Version: 5.1.2
 - Device: iPhone 11 - iPhone 15 Pro max
 - OS: iPhone 17.x.x

**Possible Solution**
I think if it possible, try to see initialization of viewcontroller that shows banner as overlay in front of the application window. Referencing from any documentation about this error, it should be created because of **the code tries to access properties from the view before super.init()**

**Additional context**
-

**Comment by TimotiusLeonardo** [comment]
@nishant-clevertap

**Comment by akashvercetti** [comment]
@TimotiusLeonardo The trait collection error was fixed in v5.2.1 https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/5.2.1

Could you please try updating to it or the latest version and giving it a run?

**Comment by TimotiusLeonardo** [comment]
Okayy @akashvercetti Thank you for your fast respond 🙏🏻 I already update it to 6.2.1 in our next release, let see if the crash still occurred in our latest release

**Comment by TimotiusLeonardo** [comment]
I ll close this issue for now until we found the same crash with updated release
