### ISSUE TITLE
CleverTap.sharedInstance()?.markRead() Crash

### ISSUE THREAD

**Issue by AssyriaGameStudio** [CleverTap/clevertap-ios-sdk#34]
I'm integrating a custom implementation of the In-App-Inbox, and unfortunately I'm experiencing a crash on iOS 13.

Prior to installing iOS 13 the same code was working. However since installing iOS 13 I'm getting the following error messages / warnings on launch:

`CoreData: fault: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.

CoreData: warning: Property 'json' on Entity 'CTMessage' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.

CoreData: warning: Property 'tags' on Entity 'CTMessage' is using nil or an insecure NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead.`

Then when I call "CleverTap.sharedInstance()?.markRead([SOME_CLEVER_TAP_MESSAGE])" I'm getting a crash with a 100% repo rate... With the debugger showing:

"libc++abi.dylib: terminating with uncaught exception of type NSException".

As soon as I comment out "CleverTap.sharedInstance()?.markRead([SOME_CLEVER_TAP_MESSAGE])" it works perfectly (aside from obviously not reporting the message as read).

**Comment by Aditi3** [comment]
Hey @AssyriaGameStudio 

Sure, we too have noticed the warnings. We will add a fix for warnings in our next release. 

Based on our testing it doesn't seem like warning could be a reason for the crash and we are unable to reproduce the crash at our end.

Can you provide us more details so that we can investigate further?

1. Describe your environment? Xcode version, SDK version, and iOS version 13.x.x
2. Are you facing this crash on a real device or simulator?
3. Can you share a demo project with us on support@clevertap.com where the crash is reproducible?

**Comment by AssyriaGameStudio** [comment]
Hey @Aditi3,
Sure - using XCode Version 11.0 (11A419c), iOS version 3.1.2, on on a real device - iPhone X, model number MQAC2B/A.

Will try and prepare a demo project before end of this week!

**Comment by Aditi3** [comment]
Hey, @AssyriaGameStudio Thanks for sharing the details. 

Additionally, help me with your CleverTap SDK version too.

**Comment by AssyriaGameStudio** [comment]
Currently on CleverTap-iOS-SDK 3.7.0 (also experienced it on 3.6.0, as the crash is what prompted the update).
