### ISSUE TITLE
iOS 13 Core Data Warning

### ISSUE THREAD

**Issue by toddgower-hiatus** [CleverTap/clevertap-ios-sdk#35]
After upgrading to Xcode 11, running our app that uses App Inbox on an iOS 13 device I get the following warning:

```
CoreData: warning: Property 'tags' on Entity 'CTMessage' is using nil or an insecure 
NSValueTransformer.  Please switch to using "NSSecureUnarchiveFromData" or a subclass of 
NSSecureUnarchiveFromDataTransformer instead.
```

**Comment by Aditi3** [comment]
Hey @toddgower-hiatus 

Thank you for bringing this up.

We too have noticed warning in iOS 13.0 related to App Inbox and we have already added the fix for the same. The fix is scheduled to be released soon.

**Comment by Aditi3** [comment]
Hi @toddgower-hiatus 

We have released the SDK with the fix for the CoreData warning.

Here is the link of the latest release that comes with warning fix
https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/3.7.1

Thanks!

**Comment by toddgower-hiatus** [comment]
Thank you @Aditi3
