### ISSUE TITLE
Xamarin SDK

### ISSUE THREAD

**Issue by jzeferino** [CleverTap/clevertap-ios-sdk#37]
Any plans to release Xamarin SDK?

**Comment by Aditi3** [comment]
Hey @jzeferino 

We are planning to release CleverTap Xamarin SDK by mid of December. Will keep you posted.

**Comment by jzeferino** [comment]
Anything I can help with that please let me know.

**Comment by Aditi3** [comment]
Hi @jzeferino 

I am glad to inform that we have released CleverTap Xamarin SDK.
Here is the Repo link: https://github.com/CleverTap/clevertap-xamarin

Thank you for your patience.
