### ISSUE TITLE
Clever Tap AutoIntgerate() does not asks for Push Notifications permission?

### ISSUE THREAD

**Issue by alvinvarghese** [CleverTap/clevertap-ios-sdk#4]
I have integreated Clever Tap in my project and initialized it in App Delegate like this.

```
 // Clever Tap
        
        CleverTap.autoIntegrate()
        CleverTap.enablePersonalization()
        CleverTap.sharedInstance().profileGetCleverTapID()
        
        let profile = ["Device" : "\(UIDevice.currentDevice().name)"]
        CleverTap.sharedInstance().profilePush(profile)
```

Also I have seen this in Clever Tap documentation.

```
You can auto integrate CleverTap into your application by calling [CleverTap autoIntegrate] (typically in application:didFinishLaunchingWithOptions:).

This will automatically notify CleverTap that your app has launched, handle device token registration, push notifications, in-app notifications and url referrer tracking, and set up a singleton instance of the CleverTap class.
```

From these it is clear that APNS works automatically, But it does not.  I have scheduled multiple Push Notifications in Clever Tap Dashboard, but none of the reached in my iPhone. I was wondering why. I have added the development and production .p12 certificates, I have did properly everything you mentioned in the documentation. And I could see that the app does not ask for "Notifications Permission", I have checked in my App's settings in iPhone Settings page, there is nothing other than my location permission request. I need your suggestions here? What is happening here? Why the notifications are not showing up in my mobile? Am I missing something in integration?

**Comment by pwilkniss** [comment]
@alvinvarghese   Sounds like you're missing the code to register the device with APNS.  

- (void)applicationDidFinishLaunching:(UIApplication *)app {
   // other setup tasks here....
 
   // Register the supported interaction types.
    UIUserNotificationType types = UIUserNotificationTypeBadge |
                 UIUserNotificationTypeSound | UIUserNotificationTypeAlert;
    UIUserNotificationSettings *mySettings =
                [UIUserNotificationSettings settingsForTypes:types categories:nil];
    [[UIApplication sharedApplication] registerUserNotificationSettings:mySettings];
 
   // Register for remote notifications.
    [[UIApplication sharedApplication] registerForRemoteNotifications];
}

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/IPhoneOSClientImp.html

Once you add that, you should start seeing the system push permissions dialog, our auto integration should kick in and things should start working.

**Comment by alvinvarghese** [comment]
I know this, But I didn't add it because the documentation said it works automatically. I thought the proxied App Delegate would take of everything.

**Comment by therohansanap** [comment]
@aaalveee true, that confused me too. Ended up doing manual configuration instead.
