### ISSUE TITLE
Question: Why have you added SDWebImage as a dependency for your SDK ?  

### ISSUE THREAD

**Issue by sudeepdunzo** [CleverTap/clevertap-ios-sdk#40]
We are trying to reduce dependencies on ObjC libraries in our codebase to improve launch times. We switched over to Kingfisher which does a great job and is completely in swift.  But since SDWebImage is a dependency for your SDK. We in effect have 2 image caching libraries in our app.

Questions: 

1. Is there a big enough use case to include an image caching library?
2. Why not use a swift 3rd part dependencies? 

We might have to consider dropping back to SDWebimage

**Comment by Aditi3** [comment]
Hi @sudeepdunzo 

Apologies for the delay response.

Answers to your queries:

1. We are using the SDWebImage cache library in our engagement channels. For example, the App Inbox uses SDWebImage for Image Cache and async loading for the image. Another Example would be In-Apps that support gifs. 

 2. Currently, our SDK is written in Objective-c language. The reason why we can't use a swift dependency. 

Having said that, we will definitely consider using the Swift dependencies when we write our SDK in the Swift language. 

Thank you!
