### ISSUE TITLE
NavigationBar Jumping Problem

### ISSUE THREAD

**Issue by Hamna21** [CleverTap/clevertap-ios-sdk#41]
Hello,

Currently using CleverTapSdk 3.7.2
There is an issue in navigation bar title for iOS 13, title slides to left. 
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/20511422/75219999-37385f00-57c0-11ea-8f3e-4354e22bf66c.gif)

There is a new property introduced for **title offset** in iOS 13 and need to set this for AppInbox navigation bar too.

**Comment by Aditi3** [comment]
Hey @Hamna21 

We are using the below code to set the Navigation Title:
`self.navigationItem.title = @"Notifications"` in our App Inbox View Controller and that should not result in title to shift left.

Additionally, I've tried reproducing the same at our end and it seems to be working correctly.

Can you share a demo project with us on support@clevertap.com where the above is reproducible?

Thank you.
