### ISSUE TITLE
APNS bad device token

### ISSUE THREAD

**Issue by tapannathvani** [CleverTap/clevertap-ios-sdk#43]
Hello,

We are getting Technical error for iOS. What is the exact meaning of it and how can we solve it?

![Screenshot 2020-03-23 at 12 39 12 PM](https://user-images.githubusercontent.com/10368955/77291076-89a76580-6d03-11ea-8856-44eee5f48f0f.png)

**Comment by Aditi3** [comment]
Hi @tapannathvani 

The error specifies device token was bad. You get this error when you try to send the notification with a wrong certificate. 

Please verify the configuration of the CleverTap dashboard. It should APNs push mode: Development/ Production with a valid development/ production certificate in Push Setting for iOS.

Thank you!

**Comment by tapannathvani** [comment]
Sorry but I found out the issue but forget to close it. Yes you are right was checking production app with development certificate. Closing this issue.
