### ISSUE TITLE
SDWebImage Dependency issue for CleverTap ver 3.7.3

### ISSUE THREAD

**Issue by ajeetpratap** [CleverTap/clevertap-ios-sdk#44]
I am getting this error when updating the CleverTap pod to the latest version.
`CocoaPods could not find compatible versions for pod "SDWebImage/Core":
  In snapshot (Podfile.lock):
    SDWebImage/Core (= 4.4.8)`

  In Podfile:
   ` CleverTap-iOS-SDK (= 3.7.3) was resolved to 3.7.3, which depends on
      SDWebImage (~> 5.1) was resolved to 5.1.0, which depends on
        SDWebImage/Core (= 5.1.0) 
SDWebImage/GIF was resolved to 4.4.8, which depends on
      SDWebImage/Core (= 4.4.8)`

**Comment by Aditi3** [comment]
Hi @ajeetpratap 

Looking at the error description what I am understanding is that your Application is pointed to version 4.x SDWebImage where CleverTap iOS SDK is using  SDWebImage v5.x. Hence, CocoaPods could not find compatible versions.

To fix the error, you need to update your SDWebImage to version 5.x.

Hope this helps!
