### ISSUE TITLE
MessageTags on Navigation bar

### ISSUE THREAD

**Issue by Hamna21** [CleverTap/clevertap-ios-sdk#45]
Hello,

I have been facing issue with AppInbox screen.

When I add message tags to the the style of CleverTapInboxViewController, the CleverTap library  adds a segmented control to navigation bar. If I push a new controller from AppInbox screen when a user clicks on notification item, the segmented view doesn't get removed and it has to be explicitly removed. 

As soon as a new controller is pushed from AppInbox screen or if its dismissed, the segmented view should be implicitly removed as it is implicitly added by the CleverTap SDK. 

This is the code from library which adds the view:
https://github.com/CleverTap/clevertap-ios-sdk/blob/f50fc19b8de30222f66a5cc708d87df72f2dc282/CleverTapSDK/Inbox/controllers/CleverTapInboxViewController.m#L224

This is my code to show AppInbox:
```
 if let inboxController = CleverTap.sharedInstance()?.newInboxViewController(with: style, andDelegate: self) {
            inboxController.hidesBottomBarWhenPushed = true
            self.navigationController?.pushViewController(inboxController, animated: true)
        }
```
Thank you!

**Comment by Hamna21** [comment]
Hello @Aditi3,

Any update regarding this issue?

Thank you!

**Comment by Aditi3** [comment]
Hi @Hamna21 

Apologies for the delay in getting back to you.

I see you're implementing `pushViewController:animated:`. We recommend presenting a CleverTap App Inbox view controller modally. 

Nonetheless, we've noted this behavior and the code suggested by you related to the segment control. I request you to allow us some time to debug more here and we will get back with an update shortly. 

Thanks,
Aditi

**Comment by Hamna21** [comment]
Thank you for your reply @Aditi3.

Well I have to open a deeplink (push a new view controller) when a user clicks on a notification. In case of presenting the CleverTap App Inbox view controller modally, the UX is not very nice. There should be an option of using both cases. 

Waiting for more updates on this. Thanks!

**Comment by Aditi3** [comment]
Hi @Hamna21

Sorry for not responding earlier! We have been trying to reproduce the scenario explained in your previous comments and have been able to replicate the same at our end. I have added a solution to handle the same in our development branch. It will be included in our next release. You can expect the release by end of this month as the fix comes with a new feature.

For now, and considering you can't implement the recommended way of presenting the CleverTap App Inbox, the quick workaround would be to edit **CleverTapInboxViewController** class in your Project and add the code to remove segmentedControlContainer from the Superview.

Helping code snippet: 

```
- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:YES];
    if (self.segmentedControlContainer) {
        [self.segmentedControlContainer removeFromSuperview];
    }
}
```
Thank you for notifying.

**Comment by Hamna21** [comment]
Hello @Aditi3,

Thank you for the update. Waiting for the next release 👍

**Comment by Aditi3** [comment]
Hi @Hamna21 

We have released the CleverTap iOS SDK that comes with this fix.
Release link: https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/3.8.0

Thank you again for bringing this up!
