### ISSUE TITLE
Carthage build does not include SDWebImage

### ISSUE THREAD

**Issue by peymankh** [CleverTap/clevertap-ios-sdk#46]
Ideally this should be used in a separate framework so that users are not forced to get SDWebImage or the UI part of CleverTap. But as a fix it'll be useful to include SDWebImage as a Carthage dependency.

**Comment by Aditi3** [comment]
Hi @peymankh 

We're including SDWebImage in our [Vendors](https://github.com/CleverTap/clevertap-ios-sdk/tree/master/Vendors) directory. 

Could you try the following steps to link SDWebImage into your project? 
1. In your Project, go to Carthage folder 
2. Select clevertap-ios-sdk under Checkouts 
3. Drag the built SDWebImage.framework from Vendors into your Frameworks and Libraries

Also, please allow us some time to check if we can find a way around to automatically link SDWebImage.

Thank you

**Comment by peymankh** [comment]
Thanks for the suggestion. 

It’d be great if you could separate out Main CleverTap framework from UI framework and link any UI related dependencies there so that users don’t have to fetch all those extra dependencies unless they need to use the UI frameworks.
