### ISSUE TITLE
OS Version reported as "Others"

### ISSUE THREAD

**Issue by calvarez-ov** [CleverTap/clevertap-ios-sdk#47]
Hello,

About 11% of events for iOS users in our CleverTap production instance have `Others` for the `OS Version` field. What can cause this?

On our test instance, we also see some specific devices reporting `Others` for the `OS Version`. We can see this value in the user profile.

This problem is not limited to any specific iPhone model.

**Comment by Aditi3** [comment]
Hi @calvarez-ov 

The necessary device information is stored internally in a database containing different types of versions. We regularly work on updating the database for any new/missed out OS versions.

These users who have 'others' must be on iOS 13.4 version.
Nonetheless, we’ve updated our database with the iOS 13.4 record. This should be working correctly now. 

Thank you for reporting this and sorry for the inconvenience caused.
