### ISSUE TITLE
How can I get Install Referrer Source from the SDK?

### ISSUE THREAD

**Issue by prdpsingh402** [CleverTap/clevertap-ios-sdk#48]
Hello Aditi ma'am

I need to know that How can I get Install Referrer Source from the SDK?

I look into the source code and I found a function.

"- (void)pushInstallReferrerSource:(NSString *_Nullable)source
                           medium:(NSString *_Nullable)medium
                         campaign:(NSString *_Nullable)campaign;"

Where I have to call this function and how it will call after App installation. Because in android we have a broadcast receiver which let us know that App has been installed so it will work like as android or is there any different approach. 

Thanks in Advance

**Comment by Aditi3** [comment]
Hi @prdpsingh402 

iOS as a platform as opposed to Android does not expose the UTM parameters of the link which were used to install the app on the App store out of the box.

We have exposed the above method to help developers pass the attribution information in case they are able to access the same.

There are workarounds available to make this easier but I would recommend writing to support@clevertap.com.

Thank you!

**Comment by prdpsingh402** [comment]
Hello Aditi ma'am,

Thanks for writing me back.

So, as an iOS developer Do you have any idea that how we can get UTM parameters during installation?

Thank you

**Comment by Aditi3** [comment]
Hi @prdpsingh402 

I would request you to write to support@clevertap.com to take the discussion forward.
