### ISSUE TITLE
Rare crash on CTInboxController.m - Line 204

### ISSUE THREAD

**Issue by AssyriaGameStudio** [CleverTap/clevertap-ios-sdk#49]
Getting a fairly rare crash in our iOS app related to the CleverTap library it seems. Firebase Crashyltics stack trace below:

<img width="1440" alt="Screenshot 2020-04-16 at 19 15 11" src="https://user-images.githubusercontent.com/465214/79491933-1bf70c80-8017-11ea-803b-dc3fcbbdc65e.png">

**Comment by Aditi3** [comment]
Hi @AssyriaGameStudio 

We haven't been able to reproduce the crash at our end. Nonetheless, we are still working on it to understand the cases where it could happen. In case we are able to reproduce the same, we would surely get it fixed in upcoming SDK release.

Thank you!

**Comment by Hamna21** [comment]
Hello @Aditi3,

I also rarely experience this crash in my production app.

**Comment by ravirajw** [comment]
Even we are also facing a crash in CTInboxController

![Screenshot 2020-12-07 at 1 46 20 PM](https://user-images.githubusercontent.com/7764874/101325891-7e489a00-3892-11eb-820e-1292e8ce7470.png)
