### ISSUE TITLE
CleverTapAppDelegateSurrogate App Crash

### ISSUE THREAD

**Issue by iosdeveloper480** [CleverTap/clevertap-ios-sdk#5]
Could not cast value of type 'CleverTapAppDelegateSurrogate' (0x100734148) to 'MyApp.AppDelegate' (0x10072fd50).

After integrating CleverTap in AppDelegate.. When i call this one in any class 
let appDelegate = UIApplication.sharedApplication().delegate as! AppDelegate

Then the about Error shows in console and App Crashed.........

Please anyone help me... Whats i am doing wrong.

**Comment by pwilkniss** [comment]
@iosdeveloper480  our automatic integration option inserts a proxy object as the app delegate, if you need to do that cast then please switch to the manual integration of the SDK.   
See more info here:  https://support.clevertap.com/docs/ios/getting-started.html#sdk-integration
