### ISSUE TITLE
Push Impressions

### ISSUE THREAD

**Issue by Hamna21** [CleverTap/clevertap-ios-sdk#51]
Hello,

I am trying to implement Push Impressions. I installed CleverTapSDK for NotificationService and included recordNotificationViewedEven:

```
override func didReceive(_ request: UNNotificationRequest, withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void) {
		// call to record the Notification viewed
		CleverTap.sharedInstance()?.recordNotificationViewedEvent(withData: request.content.userInfo)
        super.didReceive(request, withContentHandler: contentHandler)
    }
```

I am still not getting any data when user dismisses a notification. 
What further steps need to be taken? 
Thank you!

**Comment by Blankz** [comment]
I'm stuck too 

how to fix it

@Hamna21
