### ISSUE TITLE
Mobile Push Notifications opt-out

### ISSUE THREAD

**Issue by blankaorosz** [CleverTap/clevertap-ios-sdk#54]
I am working on an iOS application and I am not able to opt-out the `Mobile Push Notifications` property in my CleverTap profile (it is showing the green mark).

<img width="463" alt="Screenshot 2020-05-21 at 13 00 50" src="https://user-images.githubusercontent.com/32616566/82552870-3f0b6380-9b63-11ea-8cab-bd448a09656e.png">

I am using the following function and it is working fine with the `Emails` property:
```
 func update() {
        let profileProperties: [String: Any] = [
            "MSG-email": false,
            "MSG-sms": false,
            "MSG-push": false
        ]
        CleverTap.sharedInstance()?.profilePush(profileProperties)
}
```
but the `Mobile Push Notifications` stays green.

Also, I have tried to change it from postman (with https://api.clevertap.com/1/upload)

```
{
  "d": [{
	"identity": "email@example.com",
	"type": "profile",
	"profileData": {
		"MSG-push": false,
		"MSG-email": false
	}
  }]
}
```
but it did the same, only changed the value of the Email.

**Comment by Aditi3** [comment]
Hi @blankaorosz 

Thank you for sharing the above details.

Could you also enable CleverTap Debug log for your Application and share it with us on support@clevertap.com so we can investigate further?

**Comment by Aditi3** [comment]
Additionally, it will be helpful if you can share the CleverTap Dashboard profile link with us.

**Comment by Aditi3** [comment]
Closing it, feel free to reopen if you need further help or you can also write to support@clevertap.com.
