### ISSUE TITLE
Swizzling bug

### ISSUE THREAD

**Issue by josephlord** [CleverTap/clevertap-ios-sdk#62]
This isn’t an immediate issue for me but I thought I should flag it.

I was just trying the swizzling (autoIntegrate) to see if it helped the silent notification issues I’m having and while looking at the code I saw this (in CleverTap.m lines 376-397):
```
            } else if (class_getInstanceMethod(ncdCls, NSSelectorFromString(@"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:"))) {
                sel = NSSelectorFromString(@"userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:");
                __block NSInvocation *invocation = nil;
                invocation = [ncdCls ct_swizzleMethod:sel withBlock:^(id obj, UNUserNotificationCenter *center, UNNotificationResponse *response, void (^completion)(UIBackgroundFetchResult result) ) {
                    [CleverTap handlePushNotification:response.notification.request.content.userInfo openDeepLinksInForeground:YES];
                    [invocation setArgument:&center atIndex:2];
                    [invocation setArgument:&response atIndex:3];
                    [invocation setArgument:&completion atIndex:4];
                    [invocation invokeWithTarget:obj];
                } error:nil];
            }
        }
        if (class_getInstanceMethod(cls, NSSelectorFromString(@"application:didReceiveRemoteNotification:fetchCompletionHandler:"))) {
            sel = NSSelectorFromString(@"application:didReceiveRemoteNotification:fetchCompletionHandler:");
            __block NSInvocation *invocation = nil;
            invocation = [cls ct_swizzleMethod:sel withBlock:^(id obj, UIApplication *application, NSDictionary *userInfo, void (^completion)(void) ) {
                [CleverTap handlePushNotification:userInfo openDeepLinksInForeground:NO];
                [invocation setArgument:&application atIndex:2];
                [invocation setArgument:&userInfo atIndex:3];
                [invocation setArgument:&completion atIndex:4];
                [invocation invokeWithTarget:obj];
            } error:nil];
```
I’m 85% sure that the blocks are the wrong way round on these two swizzles. The application:didReceiveRemoteNotification:fetchCompletionHandler is the now whose fetchCompletionHandler takes a UIBackgroundFetchResult argument not the userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:

**Comment by Aditi3** [comment]
Hi @josephlord 

Sorry for not responding earlier! We have been trying to reproduce the scenario explained and have been able to replicate the same at our end.

Thank you for the feedback. We will be releasing an update to the SDK fixing the problem by this week.

**Comment by josephlord** [comment]
Thanks. No problem. I think it might not affect behaviour because swizzled Obj-C blocks aren’t really type safe so the declarations being wrong may have no effect but I thought I should let you know anyway.

**Comment by Aditi3** [comment]
Yeah, it might not be affecting the behavior and functionality for our SDK users. Nonetheless, we have added a fix for the declarations as well.

We agree with you **fetchCompletionHandler** of the `application(_:didReceiveRemoteNotification:fetchCompletionHandler:)` method has the **UIBackgroundFetchResult** argument in the case of the Silent Push Notifications. 

Thank you for bringing this up. We appreciate your feedback.
