### ISSUE TITLE
[AppInbox] The list always refreshed after pop view controller.

### ISSUE THREAD

**Issue by sukrit1808** [CleverTap/clevertap-ios-sdk#66]
Hi,

Now I'm using the App Inbox view controller for displaying as my notifications page. It seems working well. 

But when I push to the new page and then pop to App Inbox view again. The list will be refreshed and scroll to the top.

I'm not sure Is it an issue for App Inbox SDK or not?

**Comment by Aditi3** [comment]
Hi @sukrit1808 

I am assuming you've implemented App Inbox with the message tabs. Yes, in that case, CleverTap SDK refreshes the list and scroll to the top. 

In the current implementation, we've aforementioned as functionality to handle data refresh logic when message tabs are present.
