### ISSUE TITLE
Pods SDweb lib usage conflicts

### ISSUE THREAD

**Issue by Abhishek9634** [CleverTap/clevertap-ios-sdk#68]
I have a project in which we used this SDK and also have SDweb externally used as well.
if we try to update SDWeb library, it breaks 

```
[!] CocoaPods could not find compatible versions for pod "SDWebImage/GIF":
  In Podfile:
    CleverTap-iOS-SDK was resolved to 3.5.0, which depends on
      SDWebImage/GIF (~> 4.0)

None of your spec sources contain a spec satisfying the dependency: `SDWebImage/GIF (~> 4.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

**Comment by Aditi3** [comment]
Hi @Abhishek9634 

Looking at the error description what I am understanding is that your Application is pointed to a different version of SDWebImage whereas CleverTap iOS SDK v3.5.0 is using SDWebImage v4.x. Hence, CocoaPods could not find compatible versions.

If you're using v5.x of SDWebImage, I would recommend installing the latest version of our SDK. We've added support for SDWebImage v5.x in our release version 3.6.0 and above.

Check our Change Log [here](https://github.com/CleverTap/clevertap-ios-sdk/blob/master/CHANGELOG.md).

Hope this helps!

**Comment by hb2708** [comment]
@Abhishek9634 @Aditi3 to add to this i do face the same problem with applozic ios sdk and clevertap ios sdk. 
Problem here is both use `SDWebImage` but not the same version so i can not install the `applozic` using pods as it keeps giving problem. Can you guys find a better solution? May be try not specifying the version for `SDWebImage` or allow to support range of versions instead of one.

**Comment by hb2708** [comment]
@Abhishek9634 @Aditi3 did anyone managed to take a look at this?

**Comment by Aditi3** [comment]
hi @hb2708 

Based on my experience I have had with **SDWebImage** that made us specify the version in our podspec file.

**SDWebImage** had done some changes in version 5.x which required modification at their user base as well. We too had to update the code while updating SDWebImage to 5.x. 

Well, this is one of the examples and in my understanding, it's a standard practice to specify the version of the dependencies to ensure your project build is successful.

Currently, we support the 5.x series of **SDWebImage**.

Still, if the user runs into an issue and then, I would recommend to have a look at our [changelog](https://github.com/CleverTap/clevertap-ios-sdk/blob/master/CHANGELOG.md) and verify which version of SDWebImage is compatible with their project structure and install that release of ours.

Thank you!

**Comment by gyulavoros** [comment]
@Aditi3 did you consider to get rid of `SDWebImage` and implement the required functionality manually, only using APIs provided by Apple? I still find it bloat that we have to ship and all of our customers have to download. It's not ideal either way; developers who are using `SDWebImage` might depending on another version, and developers who don't use it, don't want to have it as a transitive dependency.
