### ISSUE TITLE
Manual Integration : CleverTapAppDelegateSurrogate ?

### ISSUE THREAD

**Issue by kalidosstesark** [CleverTap/clevertap-ios-sdk#7]
I got below  error. Please guide me.  Whats I am doing wrong ?

am using swift 3

**my code :** 

`  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        CleverTap.autoIntegrate()
 return true
}`

 `class func SharedDelegate() -> AppDelegate {
        return UIApplication.shared.delegate as! AppDelegate
    }`

**Could not cast value of type 'CleverTapAppDelegateSurrogate' (0x104b89260) to 'MyApp.AppDelegate' (0x104b641f0**

**Comment by pwilkniss** [comment]
@kalidosstesark  see  https://github.com/CleverTap/clevertap-ios-sdk/issues/5
