### ISSUE TITLE
Feature Request: Swift Package Manager Support

### ISSUE THREAD

**Issue by ragzy15** [CleverTap/clevertap-ios-sdk#70]
Please provide support for Swift Package Manager

**Comment by Aditi3** [comment]
Hi, @ragzy15 Thank you for submitting the Feature Request. I will take this up for discussion with our engineering team and keep you updated here.

**Comment by domagojb** [comment]
I want to +1 this. This would make integration 100x easier and less painful than manual integration for people who don't use Cocoapods.

**Comment by ragzy15** [comment]
Hi @Aditi3, is there any update regarding swift package support?

**Comment by dhadseamit** [comment]
Please add support for SPM

**Comment by PratikThakareIos** [comment]
Please add support for swift package manager

**Comment by Aditi3** [comment]
Hi All, 

Thank you for your feedback 👍 

We have taken up this request in our current quarter. The support for Swift Package Manager will be available in the first/ second week of October.

Best,
Aditi

**Comment by domagojb** [comment]
Thank you!

**Comment by ragzy15** [comment]
Thanks for your support @Aditi3 👍

**Comment by baraeb92** [comment]
Any updated related to this @Aditi3 , seems like the latest version 3.9.1 still doesn't mention any support for SPM

Is it still planned for October release or pushed further back to November or later? 

https://github.com/CleverTap/clevertap-ios-sdk/releases

**Comment by Aditi3** [comment]
Hi @baraeb92 

Well, yes our latest release includes iOS 14.0 updates and some minor fixes. Due to the unexpected assignments, there's a delay in enabling swift package manager support.

Nevertheless, Swift Package Manager is next up in our iOS Roadmap. I will keep you posted with the timeline once we finalize internally.

**Comment by Aditi3** [comment]
Follow the progress at https://github.com/CleverTap/clevertap-ios-sdk/tree/feature/swift-pm. PRs and Suggestions welcome!

**Comment by ragzy15** [comment]
Hi @Aditi3, can you provide a timeline as when the version 3.9.2 will be released with swift package manager support?

**Comment by Aditi3** [comment]
Hey @ragzy15, Apologies for the delayed response. There’s a delay in the release of version 3.9.2 due to unforeseen issues and we're planning to append another feature request in the same version.

At present, we're aiming to release version 3.9.2 will include Swift Package Manager support by the end of December.

**Comment by ragzy15** [comment]
Hi @Aditi3 any updates regarding release of swift package manager support?

**Comment by cclaflin89** [comment]
+1 

I found clevertap uses SDWebImage package which I added in SPM, thus I have two SDWebImage libraries(one in cocoapods and the other in SPM) in the project.

Found this in Podfile.lock file.
  - CleverTap-iOS-SDK (3.9.1):
    - SDWebImage (~> 5.1)
 
And I'm getting this error:

Class SDAnimatedImage is implemented in both /private/var/containers/Bundle/Application/....app/Frameworks/SDWebImage.framework/SDWebImage (0x107f367f0) and /private/var/containers/Bundle/Application/....app/MyApp (0x1059f8248). One of the two will be used. Which one is undefined.

**Comment by roimulia2** [comment]
Hey @Aditi3, any news about the official (tag) SPM support? Is feature/swift-pm considered a stable release?

**Comment by Aditi3** [comment]
I have taken up Swift Package Manager release discussion internally with my team as some High priority task. Allow me some time to share a new timeline for the official release.

**Comment by Aditi3** [comment]
Hi All,

We will be releasing Swift Package Manage support by mid-March.

**Comment by roimulia2** [comment]
Hey @Aditi3, It's already April :) 
Is it officially released yet?

**Comment by doublegucci** [comment]
How does this work somebody to talk to me I've been trying to learn this I can't figure it all out just got it￼

**Comment by Aditi3** [comment]
The official release will be out in a day or two. Thanks for your patience.

**Comment by roimulia2** [comment]
@Aditi3 Can't wait! Thanks :)
