### ISSUE TITLE
Carthage error on 3.8.1

### ISSUE THREAD

**Issue by peymankh** [CleverTap/clevertap-ios-sdk#72]
Getting the following error when using the latest SDK.

```
A shell task (/usr/bin/xcrun xcodebuild -project ${PROJECT_DIR}/Carthage/Checkouts/clevertap-ios-sdk/ObjCStarter/Pods/Pods.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:
xcodebuild: error: Unable to read project 'Pods.xcodeproj' from folder '${PROJECT_DIR}/Carthage/Checkouts/clevertap-ios-sdk/ObjCStarter/Pods'.
        Reason: Project ${PROJECT_DIR}/Carthage/Checkouts/clevertap-ios-sdk/ObjCStarter/Pods/Pods.xcodeproj cannot be opened because it is missing its project.pbxproj file.
```

**Comment by Aditi3** [comment]
Hi @peymankh 

Thank you for bringing this up. We too have noticed this issue a few days and merged a fix for the same in our master branch. The release is planned to go in a day or two.

Right now, If you want to implement changes released in version 3.8.1, I would recommend checking out the master branch using Carthage. 

The branch can be referenced by name by using the following in your Cartfile: 

``` github "CleverTap/clevertap-ios-sdk" "master"  ```

Sorry for the trouble caused to you and will keep you posted with the release.

**Comment by peymankh** [comment]
That’s great @Aditi3 and thanks for your quick reply. Will be waiting for the SDK update before making changes.

**Comment by Aditi3** [comment]
Hi @peymankh 

We have released the SDK that comes with Carthage error fix.
Release link: https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/3.8.2

Hope this helps :)

**Comment by peymankh** [comment]
Perfect, thanks. Will give it a try later this week 👍 👌
