### ISSUE TITLE
iOS 14 Privacy Requirements

### ISSUE THREAD

**Issue by AlexGingell** [CleverTap/clevertap-ios-sdk#74]
Hi there,

Is there any commentary or documentation on how the iOS 14 App Tracking Transparency and Privacy changes affect the usage of the CleverTap SDK itself going forward?

That is, if we are just using the CleverTap SDK for our own private analytics, does CleverTap require us to use the AppTrackingTransparency framework or adjust our approach to privacy in any way. For example, in order to give CleverTap access to the IDFA for unique user profiling?

https://developer.apple.com/documentation/apptrackingtransparency?language=objc

Best,

Alex

**Comment by Aditi3** [comment]
Hi @AlexGingell 

We’re working on an official blog which will include all the details about how iOS 14 App Tracking Transparency and Privacy changes affect the usage of the CleverTap SDK.

The blog will also provide an overview of the changes (especially the IDFA tracking) that we will incorporate in our SDK post iOS 14 is out of beta and released globally. 

The post is planned to go live by this week. I will share the link here once it is up.

Thank you,
Aditi

**Comment by Aditi3** [comment]
The blog is live now. @AlexGingell , you can take a look at it [here](https://clevertap.com/blog/preparing-for-ios-14-user-privacy-updates/).

**Comment by AlexGingell** [comment]
> The blog is live now. @AlexGingell , you can take a look at it [here](https://clevertap.com/blog/preparing-for-ios-14-user-privacy-updates/).

Thank you for the notification. So the conclusion I draw from the blog is that there are no specific steps to make in order to comply with these regulations if we are solely using the CleverTap SDK and were not requesting the IDFA through the SDK or via our own code.  The CleverTap SDK does not (or will not) privately make use of the IDFA and necessitate the permission dialog.

**Comment by Aditi3** [comment]
yes, you have understood rightly. In our [latest release](https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/3.9.0), we've stopped capturing IDFA and removes code that has the ability to access the device’s advertising identifier (IDFA).

Like pointed in the blog, customers can continue to use the `setCleverTapID` API to set the IDFA in the user profile after the user gives consent by opting-in.
