### ISSUE TITLE
CTNotifcation Service crash

### ISSUE THREAD

**Issue by Hamna21** [CleverTap/clevertap-ios-sdk#77]
Hello,

I am experiencing following crash in my production app for Notification Service Extension. Attaching screenshot and crash log:

[2020-09-16_07-47-47.1668_+0700-4a015e4cd492f5d9812873858e36abde0f519f52.crash.zip](https://github.com/CleverTap/clevertap-ios-sdk/files/5230538/2020-09-16_07-47-47.1668_%2B0700-4a015e4cd492f5d9812873858e36abde0f519f52.crash.zip)

![image](https://user-images.githubusercontent.com/20511422/93305021-5dceed80-f817-11ea-9b57-e6ca7a2e6099.png)

Can you please help in identifying the cause of this crash?

Thank you

**Comment by Aditi3** [comment]
Hi @Hamna21 

We will look into it and update you with our findings. Besides the stack trace, are you able to reproduce this yourself?

**Comment by Aditi3** [comment]
Closing this as it is being raised and taken up by Support.
Thanks!
