### ISSUE TITLE
Can't mute In-app messages?

### ISSUE THREAD

**Issue by zaully** [CleverTap/clevertap-ios-sdk#8]
Hey guys,

I'm using [this binary](https://github.com/CleverTap/clevertap-ios-sdk/files/880832/CleverTapSDK.framework.zip) directly as I can't use CocoaPods to include the SDK indicated in another issue so I'm not sure this is an issue for the CocoaPods version.

I found out if the app is closed (not just backgrounded) and if users tap on the iOS push notification for the in-app, the app would be launched AND in-app will be displayed automatically without any functions called to CleverTap. I'm not using AutoIntegrate() as I want to manually control the in-app dialogs.

My AppDelegate is pretty simple:
```swift
import UIKit
import CleverTapSDK

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        CleverTap.changeCredentials(withAccountID: "some_id", andToken: "some_token")
        return true
    }
    
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        let deviceTokenString = deviceToken.map { String(format: "%02.2hhx", $0) }.joined()
        print("Device token: \(deviceTokenString)")
        CleverTap.sharedInstance().setPushToken(deviceToken)
    }

    func applicationWillResignActive(_ application: UIApplication) {
    }

    func applicationDidEnterBackground(_ application: UIApplication) {
    }

    func applicationWillEnterForeground(_ application: UIApplication) {
    }

    func applicationDidBecomeActive(_ application: UIApplication) {
    }

    func applicationWillTerminate(_ application: UIApplication) {
    }
}
```

thanks for your time.

**Comment by pwilkniss** [comment]
@zaully  not sure I'm quite following you here.   Would you mind dropping an email to support@ clevertap.com with your account info and as much context as you can re: what you are trying to do. We'll get you taken care of there.  Thanks.

**Comment by zaully** [comment]
@pwilkniss yep will do it. thanks.
