### ISSUE TITLE
For iMessage App Extensions and for iMessage Standalone apps

### ISSUE THREAD

**Issue by NikhilManapure** [CleverTap/clevertap-ios-sdk#9]
How to integrate CleverTap with iMessage App Extensions and iMessage Standalone apps?

I could see an example for extension but not for a standalone iMessage app

**Comment by Aditi3** [comment]
Hey @NikhilManapure 

Apologies for the delay!

Below is the procedure to integrate CleverTap for a standalone iMessage App

1. Add CleverTap SDK to your Podfile

 `target 'YOUR_APP_EXTENSION_TARGET_NAME' do
       pod 'CleverTap-iOS-SDK', :subspecs => ['AppEx']
  end`

2.  You will need to add your CleverTap credentials in the Info.plist file in your App Extension target.

3. Set the CLEVERTAP_APP_EXTENSION Preprocessor Macro in your Xcode App Extension build settings.

4. Import **CleverTapAppEx** to your AppDelegate.h file. Make sure, to Import **CleverTapAppEx** into every class where you plan to record user events.

5. An example of recording a User Event called Product Viewed. 

`        CleverTap.sharedInstance().recordEvent("Product Viewed")
`
Hope this helps!

**Comment by Aditi3** [comment]
Closing it, feel free to reopen if you need further help or you can also write to support@clevertap.com.

**Comment by NikhilManapure** [comment]
Thanks @Aditi3 , will try this out and let you know.
