### ISSUE TITLE
onUserLogin method is throwing error as identity got appended

### ISSUE THREAD

**Issue by AppleNinja** [CleverTap/clevertap-ios-sdk#99]
We followed the following steps to reproduce the issue:

- To test if you have correctly implemented the same, please perform the below simple steps: 
- Install the app & launch it. Login using an existing/already registered profile on the app, say Email ID1/Phone number1 ( whichever is used for user login ).
- Check on the CleverTap dashboard if the email/identity is getting populated for this profile as expected.
- Kill the app and re-launch it.
- Now on the same device, register using another NEW profile which is not registered with the app already, say with EmailID2/Phone number2, and check if a separate profile is created on the CleverTap dashboard for this user. If yes, then onUserLogin() has been implemented correctly.

On the CleverTap Dashboard its showing as appended

	Identity Set | arunachalam.k@rizek.com,2162 | ID | Appended | false | SDK |

CleverTap.TEST-W44-79K-WZ6Z: onUserLogin: either don't have identifier or device is anonymous, associating profile {
    AcquistionType = "Mobile app";
    AppVersion = "1.3.3";
    Email = "arunachalam.k@rizek.com";
    Gender = male;
    Identity = 2162;
    Name = "Arunachalam K";
    Phone = "+971585251997";
    Platform = iOS;
} with current user profile

**Comment by Aditi3** [comment]
hi @AppleNinja 

I've tried to reproduce the issue but it's working correctly here. Could you confirm/ verify you're not sending the same `Identity` for both the users?

 It appears the `Identity` sent is same for User 1 and User 2 by looking at the shared debug Log and dashboard message.

**Comment by Aditi3** [comment]
I am going to close this issue here. If you have additional queries, please raise a support request via the CleverTap Dashboard.
